"""
Daily financial knowledge card — /api/knowledge/today

Uses today's date as a deterministic seed so every user sees the same
card on the same day.  No external network calls required.
"""

from fastapi import APIRouter
from datetime import date
import random

router = APIRouter()

# ─────────────────────────────────────────────────────────────────────────────
# Knowledge base (30 items)
# ─────────────────────────────────────────────────────────────────────────────
_KB = [
    # ── 估值类 ──────────────────────────────────────────────────────────────
    {
        "topic": "市盈率 P/E Ratio",
        "category": "估值",
        "content_zh": "市盈率（P/E）是衡量股票估值高低最常用的指标，反映投资者愿意为每1元净利润支付多少股价。P/E越低，股票相对越便宜；但低P/E不代表一定值得买，还需结合行业和成长性综合判断。",
        "content_en": "The Price-to-Earnings (P/E) ratio is the most widely used valuation metric, showing how much investors pay for every ¥1 of earnings. A lower P/E generally indicates cheaper valuation, but must be evaluated alongside industry norms and growth prospects.",
        "key_formula": "P/E = 股价 (Price) ÷ 每股收益 (EPS)",
        "example": "股价 60 元，EPS 3 元 → P/E = 20 倍。意味着按当前盈利需 20 年回本。",
        "difficulty": "⭐",
        "tags": ["估值", "基本面分析"],
    },
    {
        "topic": "市净率 P/B Ratio",
        "category": "估值",
        "content_zh": "市净率（P/B）将股价与每股净资产（账面价值）相比，常用于评估银行、保险等重资产行业。P/B < 1 意味着股价低于公司账面价值，可能是低估机会，也可能说明资产质量有问题。",
        "content_en": "The Price-to-Book (P/B) ratio compares stock price to book value per share. It is particularly useful for asset-heavy sectors like banking. P/B < 1 can signal undervaluation, but may also reflect poor asset quality.",
        "key_formula": "P/B = 股价 (Price) ÷ 每股净资产 (Book Value per Share)",
        "example": "某银行股价 5 元，每股净资产 8 元 → P/B = 0.625，低于 1，存在折价。",
        "difficulty": "⭐",
        "tags": ["估值", "银行股"],
    },
    {
        "topic": "市销率 P/S Ratio",
        "category": "估值",
        "content_zh": "市销率（P/S）用市值除以年营收，适用于暂时亏损但营收高速增长的科技公司（此时P/E无意义）。P/S 越低通常越便宜，但高P/S公司若能维持高增速也可能物有所值。",
        "content_en": "The Price-to-Sales (P/S) ratio divides market cap by annual revenue. Useful for unprofitable but fast-growing tech companies where P/E is meaningless. Lower P/S generally suggests cheaper valuation.",
        "key_formula": "P/S = 总市值 ÷ 年营收  （或  股价 ÷ 每股营收）",
        "example": "某科技公司市值 100 亿，年营收 20 亿 → P/S = 5 倍。",
        "difficulty": "⭐⭐",
        "tags": ["估值", "科技股"],
    },
    {
        "topic": "EV/EBITDA",
        "category": "估值",
        "content_zh": "EV/EBITDA 是企业价值除以息税折旧摊销前利润，排除了资本结构和会计差异的干扰，常用于跨国、跨行业比较。比P/E更难被会计操纵，被并购方和专业机构广泛使用。",
        "content_en": "EV/EBITDA compares Enterprise Value to Earnings Before Interest, Taxes, Depreciation & Amortisation. It removes the distortions of capital structure and accounting choices, making it ideal for cross-border and cross-sector comparisons.",
        "key_formula": "EV = 市值 + 有息负债 − 现金；EV/EBITDA = EV ÷ EBITDA",
        "example": "EV 200 亿，EBITDA 20 亿 → EV/EBITDA = 10 倍，低于行业均值说明相对低估。",
        "difficulty": "⭐⭐⭐",
        "tags": ["估值", "并购分析"],
    },
    {
        "topic": "PEG Ratio",
        "category": "估值",
        "content_zh": "PEG = P/E ÷ 盈利增速（%），修正了P/E忽略成长性的缺陷。PEG < 1 通常被认为低估，= 1 为合理，> 1 偏高。适合成长股估值，对周期股效果不佳。",
        "content_en": "PEG divides the P/E ratio by the earnings growth rate (%), correcting P/E's blind spot on growth. PEG < 1 is often considered undervalued, = 1 fair value, > 1 expensive. Best for growth stocks.",
        "key_formula": "PEG = P/E ÷ 净利润增速 (%)",
        "example": "P/E = 30，净利润增速 = 30% → PEG = 1.0，估值合理。",
        "difficulty": "⭐⭐",
        "tags": ["估值", "成长股"],
    },
    {
        "topic": "DCF 折现现金流估值",
        "category": "估值",
        "content_zh": "DCF（Discounted Cash Flow）是理论上最严谨的估值方法，将企业未来所有自由现金流折算到今天的价值之和。核心假设是折现率（反映风险）和终值增速。对假设极其敏感，"垃圾进垃圾出"是常见批评。",
        "content_en": "DCF is theoretically the most rigorous valuation method, summing all future free cash flows discounted to present value. Key inputs are the discount rate (reflecting risk) and terminal growth rate. Highly sensitive to assumptions — 'garbage in, garbage out.'",
        "key_formula": "内在价值 = Σ FCFₜ / (1+r)ᵗ + 终值 / (1+r)ⁿ",
        "example": "若折现率 10%，5 年后 FCF = 10 亿，终值 100 亿，则今天价值 ≈ 68 亿。",
        "difficulty": "⭐⭐⭐",
        "tags": ["估值", "投资分析"],
    },
    # ── 技术分析类 ──────────────────────────────────────────────────────────
    {
        "topic": "K线图基础",
        "category": "技术分析",
        "content_zh": "K线（蜡烛图）起源于18世纪日本米市，每根K线记录开盘、收盘、最高、最低四个价格。阳线（红/绿）收盘>开盘，阴线（绿/红）收盘<开盘。实体越长说明多空力量越强，上下影线反映盘中的试探。",
        "content_en": "Candlestick charts originated in 18th-century Japan. Each candle records four prices: open, close, high, low. A bullish (hollow/green) candle closes above open; a bearish (filled/red) candle closes below. Long bodies indicate strong momentum; wicks show intraday probing.",
        "key_formula": "实体 = |收盘 − 开盘|；上影线 = 最高 − 实体顶；下影线 = 实体底 − 最低",
        "example": "锤头线：长下影线 + 小实体，出现在下跌末端，预示反转信号。",
        "difficulty": "⭐",
        "tags": ["技术分析", "K线"],
    },
    {
        "topic": "移动平均线 MA",
        "category": "技术分析",
        "content_zh": "移动平均线（MA）是一段时间内收盘价的算术平均，用于平滑短期波动，识别趋势方向。MA5/10 反映短期，MA20/60 反映中期，MA120/250 反映长期。均线多头排列（短期在长期上方）是上涨信号。",
        "content_en": "A Moving Average smooths price data to identify trend direction. MA5/10 reflect short-term momentum; MA20/60 represent medium-term; MA120/250 long-term. A bullish alignment (short MAs above long MAs) is a positive signal.",
        "key_formula": "MAₙ = (P₁ + P₂ + … + Pₙ) ÷ n",
        "example": "MA5 = 105，MA20 = 100，MA60 = 90 → 多头排列，趋势向上。",
        "difficulty": "⭐",
        "tags": ["技术分析", "趋势"],
    },
    {
        "topic": "MACD 指标",
        "category": "技术分析",
        "content_zh": "MACD（Moving Average Convergence Divergence）由快线DIF、慢线DEA和柱状图MACD组成。DIF金叉DEA（由下向上穿越）是买入信号；死叉为卖出信号。柱状图由负转正说明动能转强。",
        "content_en": "MACD consists of the DIF line (fast EMA minus slow EMA), the DEA signal line, and the histogram. A golden cross (DIF crossing above DEA) is a buy signal; a death cross is a sell signal. Histogram turning positive indicates strengthening momentum.",
        "key_formula": "DIF = EMA12 − EMA26；DEA = EMA9(DIF)；MACD = 2×(DIF−DEA)",
        "example": "DIF 从 -0.5 升至 +0.2 穿越 DEA（-0.1）→ 金叉，买入信号。",
        "difficulty": "⭐⭐",
        "tags": ["技术分析", "动量"],
    },
    {
        "topic": "RSI 相对强弱指数",
        "category": "技术分析",
        "content_zh": "RSI（Relative Strength Index）衡量价格涨跌的力度，取值 0-100。RSI > 70 为超买区，可能面临回调；RSI < 30 为超卖区，可能出现反弹。在趋势强烈时，RSI 可长期处于极值区间（钝化）。",
        "content_en": "RSI measures the speed and magnitude of price changes, ranging from 0 to 100. RSI > 70 signals overbought conditions (potential pullback); RSI < 30 signals oversold (potential bounce). In strong trends, RSI can remain in extreme zones for extended periods.",
        "key_formula": "RSI = 100 − 100 ÷ (1 + RS)，其中 RS = 平均涨幅 ÷ 平均跌幅",
        "example": "14日内平均涨幅 1.2，平均跌幅 0.4 → RS = 3 → RSI = 75（超买）。",
        "difficulty": "⭐⭐",
        "tags": ["技术分析", "超买超卖"],
    },
    {
        "topic": "布林带 Bollinger Bands",
        "category": "技术分析",
        "content_zh": "布林带由中轨（MA20）及上下各两倍标准差构成，反映价格波动区间。价格触及上轨可能回落，触及下轨可能反弹。布林带收窄（低波动）往往预示大行情即将到来。",
        "content_en": "Bollinger Bands consist of a middle band (MA20) plus upper and lower bands at ±2 standard deviations. Price touching the upper band may signal a pullback; lower band a bounce. Band contraction (low volatility) often precedes a significant price move.",
        "key_formula": "上轨 = MA20 + 2σ；下轨 = MA20 − 2σ",
        "example": "布林带宽度从 15 收窄至 5，随后股价单日暴涨 8%，带宽迅速扩张。",
        "difficulty": "⭐⭐",
        "tags": ["技术分析", "波动率"],
    },
    {
        "topic": "成交量分析",
        "category": "技术分析",
        "content_zh": "成交量是价格走势的"验证者"。量增价升是健康上涨；量缩价升说明上涨动力不足；量增价跌说明抛压沉重；量缩价跌是正常整理。"天量之后天价，地量之后地价"是量价关系的经典总结。",
        "content_en": "Volume validates price moves. Rising volume on price gains is healthy; rising volume on price declines signals heavy selling. Shrinking volume on gains suggests weak momentum. The saying 'peak volume precedes peak price' captures the classic volume-price relationship.",
        "key_formula": "量比 = 当日成交量 ÷ 过去5日平均成交量",
        "example": "量比 > 2.5 且价格突破阻力位，确认有效突破概率较高。",
        "difficulty": "⭐⭐",
        "tags": ["技术分析", "成交量"],
    },
    # ── 基本面类 ──────────────────────────────────────────────────────────
    {
        "topic": "营收 vs 净利润",
        "category": "基本面",
        "content_zh": "营收（Revenue）是企业销售商品/服务的总收入，净利润（Net Profit）是扣除所有成本、税费后的最终盈余。高营收低净利润说明成本高或费用大；高净利润率说明盈利能力强。两者同步增长才是最健康的状态。",
        "content_en": "Revenue is total income from sales; Net Profit is what remains after all costs and taxes. High revenue with low net profit indicates high costs; high profit margin signals strong profitability. Both growing together is the healthiest sign.",
        "key_formula": "净利润率 = 净利润 ÷ 营收 × 100%",
        "example": "营收 100 亿，净利润 15 亿 → 净利润率 15%，处于行业中等偏上水平。",
        "difficulty": "⭐",
        "tags": ["基本面", "财务分析"],
    },
    {
        "topic": "ROE 净资产收益率",
        "category": "基本面",
        "content_zh": "ROE（Return on Equity）衡量股东每1元资本能赚多少净利润，是巴菲特最重视的指标之一。ROE持续高于15%通常被认为是优质企业标志。但高ROE也可能来自高杠杆，需配合资产负债率判断。",
        "content_en": "ROE measures how much net profit a company generates per yuan of shareholders' equity — one of Buffett's favourite metrics. Sustained ROE above 15% typically signals a high-quality business, but high ROE from excessive leverage must be viewed cautiously.",
        "key_formula": "ROE = 净利润 ÷ 平均股东权益 × 100%",
        "example": "贵州茅台 ROE 长期维持 30% 以上，远高于行业均值，体现超强盈利能力。",
        "difficulty": "⭐⭐",
        "tags": ["基本面", "盈利能力"],
    },
    {
        "topic": "毛利率 vs 净利率",
        "category": "基本面",
        "content_zh": "毛利率 = (营收 - 营业成本) / 营收，反映产品定价能力；净利率 = 净利润 / 营收，是最终盈利效率。毛利率高但净利率低，说明销售/管理/财务费用高。消费品、软件类毛利率通常高，制造业相对低。",
        "content_en": "Gross margin = (Revenue − COGS) / Revenue, reflecting pricing power. Net margin = Net Profit / Revenue, the ultimate profitability measure. High gross margin with low net margin implies high operating expenses. Consumer goods and software typically have higher margins than manufacturing.",
        "key_formula": "毛利率 = (营收 − 营业成本) ÷ 营收；净利率 = 净利润 ÷ 营收",
        "example": "白酒行业毛利率 80%+，净利率 30-50%，远超制造业毛利率 20% 水平。",
        "difficulty": "⭐⭐",
        "tags": ["基本面", "盈利能力"],
    },
    {
        "topic": "资产负债率",
        "category": "基本面",
        "content_zh": "资产负债率衡量企业的财务风险，过高说明偿债压力大，过低可能是保守经营。一般制造业 < 60% 较合理，银行可达 90%+（因其商业模式特殊）。需结合利息保障倍数一起看。",
        "content_en": "The debt-to-asset ratio measures financial risk. Too high signals heavy debt burden; too low may indicate overly conservative management. A ratio below 60% is generally reasonable for manufacturers; banks can exceed 90% due to their unique business model.",
        "key_formula": "资产负债率 = 总负债 ÷ 总资产 × 100%",
        "example": "某企业总资产 200 亿，总负债 150 亿 → 资产负债率 75%，偏高需关注偿债风险。",
        "difficulty": "⭐⭐",
        "tags": ["基本面", "偿债能力"],
    },
    {
        "topic": "现金流量表解读",
        "category": "基本面",
        "content_zh": "现金流量表分三部分：经营现金流（日常运营收支）、投资现金流（资本支出和投资）、融资现金流（借债和分红）。"利润是意见，现金流是事实"——经营现金流持续大于净利润是优质企业的重要特征。",
        "content_en": "The cash flow statement has three sections: operating, investing, and financing cash flows. 'Earnings are opinions, cash flow is fact.' Strong and sustained operating cash flow exceeding net profit is a hallmark of a high-quality business.",
        "key_formula": "自由现金流 (FCF) = 经营现金流 − 资本支出",
        "example": "某企业净利润 10 亿，经营现金流 15 亿 → 现金质量优质；若相反则需警惕。",
        "difficulty": "⭐⭐⭐",
        "tags": ["基本面", "财务分析"],
    },
    {
        "topic": "EPS 每股收益",
        "category": "基本面",
        "content_zh": "EPS（Earnings Per Share）是净利润除以总股本，反映每股对应的盈利能力。EPS增长率直接驱动股价长期上涨。注意摊薄EPS（考虑期权、可转债等稀释效应）比基本EPS更保守。",
        "content_en": "EPS divides net profit by total shares outstanding, measuring per-share earning power. EPS growth is the primary driver of long-term stock price appreciation. Diluted EPS (accounting for options and convertibles) is more conservative than basic EPS.",
        "key_formula": "EPS = 净利润 ÷ 加权平均股本",
        "example": "净利润 10 亿，总股本 5 亿股 → EPS = 2 元/股；若股价 40 元，则P/E = 20。",
        "difficulty": "⭐",
        "tags": ["基本面", "盈利能力"],
    },
    # ── 宏观经济类 ──────────────────────────────────────────────────────────
    {
        "topic": "CPI 与通货膨胀",
        "category": "宏观经济",
        "content_zh": "CPI（居民消费价格指数）衡量一篮子商品和服务的价格变化，是最常用的通胀指标。温和通胀（2%左右）对股市有利；高通胀迫使央行加息，压制股票估值；通缩则意味着经济需求萎缩。",
        "content_en": "CPI (Consumer Price Index) measures price changes of a basket of goods and services — the most widely used inflation indicator. Mild inflation (~2%) is market-friendly; high inflation forces central banks to raise rates, compressing valuations; deflation signals weak demand.",
        "key_formula": "CPI 同比 = (本月CPI ÷ 去年同月CPI − 1) × 100%",
        "example": "美联储目标通胀率 2%。2022 年 CPI 升至 9%，引发连续大幅加息。",
        "difficulty": "⭐⭐",
        "tags": ["宏观经济", "通胀"],
    },
    {
        "topic": "利率与股市的关系",
        "category": "宏观经济",
        "content_zh": "利率上升时：债券收益率提高→股票吸引力下降；企业融资成本升高→盈利承压；DCF分母变大→估值压缩。因此"利率是股市的引力"（巴菲特语）。加息周期对高估值成长股打击最大。",
        "content_en": "When interest rates rise: bond yields increase (reducing stock appeal), corporate borrowing costs climb (pressuring earnings), and DCF discount rates grow (compressing valuations). Buffett famously called interest rates 'gravity for stocks.' Rate hikes hit high-valuation growth stocks hardest.",
        "key_formula": "股票内在价值 ∝ 1 ÷ 折现率；折现率 ≈ 无风险利率 + 风险溢价",
        "example": "2022年美联储加息，纳斯达克跌约33%；高P/E科技股跌幅普遍超过50%。",
        "difficulty": "⭐⭐",
        "tags": ["宏观经济", "利率"],
    },
    {
        "topic": "GDP 与股市关系",
        "category": "宏观经济",
        "content_zh": "GDP 是衡量经济总量的指标，股市通常被称为经济的"晴雨表"，但两者关系并非线性。巴菲特指标（总市值/GDP）> 1 时历史上往往预示股市高估。股市会提前6-12个月反映经济走势。",
        "content_en": "GDP measures total economic output. Stock markets are often called economic 'barometers,' but the relationship is non-linear. The Buffett Indicator (total market cap / GDP > 1) has historically signalled overvaluation. Markets typically lead the economy by 6-12 months.",
        "key_formula": "巴菲特指标 = 股市总市值 ÷ GDP × 100%",
        "example": "2020 年底美国巴菲特指标超 200%，创历史新高，随后部分板块大幅回调。",
        "difficulty": "⭐⭐",
        "tags": ["宏观经济", "市场择时"],
    },
    {
        "topic": "美联储加息的影响",
        "category": "宏观经济",
        "content_zh": "美联储通过联邦基金利率影响全球资金成本。加息→美元走强→新兴市场资金外流→人民币贬值压力→A股承压。A股与美股的联动在北向资金时代愈发明显。降息则相反，流动性宽松利好风险资产。",
        "content_en": "The Federal Reserve's rate decisions affect global capital costs. Rate hikes → stronger USD → capital outflows from emerging markets → RMB depreciation pressure → A-share headwinds. A-share and US market linkages have strengthened in the era of Stock Connect. Rate cuts have the opposite effect.",
        "key_formula": "实际利率 = 名义利率 − 通胀率；实际利率为负时，黄金和风险资产受益",
        "example": "2022年 Fed 加息 425bp，人民币从 6.3 跌至 7.3，北向资金大幅净流出。",
        "difficulty": "⭐⭐⭐",
        "tags": ["宏观经济", "汇率"],
    },
    {
        "topic": "北向资金",
        "category": "宏观经济",
        "content_zh": "北向资金指通过沪港通、深港通流入A股市场的境外资金（因从香港往北流入大陆而得名）。北向资金被认为是"聪明钱"，其净流入/流出方向常被散户作为参考信号，但并非总是准确。",
        "content_en": "Northbound funds refer to foreign capital flowing into A-shares via the Shanghai-Hong Kong and Shenzhen-Hong Kong Stock Connect programs (flowing 'northward' from Hong Kong to mainland China). Often called 'smart money,' their flows are widely tracked, though not infallible.",
        "key_formula": "北向资金净流入 = 当日买入额 − 当日卖出额",
        "example": "某交易日北向资金净流入 100 亿元，被解读为外资看多A股信号。",
        "difficulty": "⭐⭐",
        "tags": ["宏观经济", "资金流向"],
    },
    # ── A股特有 ──────────────────────────────────────────────────────────
    {
        "topic": "涨跌停板制度",
        "category": "A股规则",
        "content_zh": "A股主板/中小板单日涨跌幅限制为 ±10%，科创板和创业板注册制新股为 ±20%，北交所为 ±30%。涨停时买单堆积但无法成交，形成排队效应；连续一字板说明市场分歧极小。",
        "content_en": "China's A-share main board limits daily price moves to ±10%. STAR Market and ChiNext (after registration-based reform) allow ±20%; the BSE allows ±30%. A limit-up close with queued buy orders signals strong demand; consecutive limit-up days show minimal selling pressure.",
        "key_formula": "涨停价 = 前收盘价 × (1 + 10%)；跌停价 = 前收盘价 × (1 − 10%)",
        "example": "前收盘 20 元 → 涨停价 22 元，跌停价 18 元（主板）。",
        "difficulty": "⭐",
        "tags": ["A股规则", "交易制度"],
    },
    {
        "topic": "T+1 交易规则",
        "category": "A股规则",
        "content_zh": "A股实行T+1交割制度，即当天买入的股票次个交易日才能卖出，但资金到账是T+1。这意味着买错了只能等到明天再卖，相比T+0（美股）流动性管理更复杂，散户无法当天高抛低吸。",
        "content_en": "A-shares operate under T+1 settlement: stocks bought today cannot be sold until the next trading day. Unlike T+0 in US markets, this limits intraday profit-taking for retail investors and increases the cost of wrong-day decisions.",
        "key_formula": "无公式。规则：T日买入 → T+1日方可卖出",
        "example": "周四买入某股，当天急跌想止损，只能等周五开盘卖出，可能损失扩大。",
        "difficulty": "⭐",
        "tags": ["A股规则", "交易制度"],
    },
    {
        "topic": "融资融券（两融）",
        "category": "A股规则",
        "content_zh": "融资是向券商借钱买股票（加杠杆做多），融券是向券商借股票卖出（做空）。两融余额是市场情绪的晴雨表：余额过高说明杠杆过重，系统风险大；余额极低说明悲观情绪蔓延。",
        "content_en": "Margin trading (融资) involves borrowing money to buy stocks, amplifying gains and losses. Short selling (融券) involves borrowing shares to sell, betting on price declines. Total margin balance is a market sentiment indicator: high balance signals excessive leverage; low balance signals pessimism.",
        "key_formula": "融资杠杆率 = 融资额 ÷ 自有资金；融券空头比例 = 融券余额 ÷ 流通市值",
        "example": "两融余额 > 1.8 万亿时，历史上A股往往处于阶段性高点。",
        "difficulty": "⭐⭐⭐",
        "tags": ["A股规则", "杠杆交易"],
    },
    {
        "topic": "创业板 vs 主板 vs 科创板",
        "category": "A股规则",
        "content_zh": "主板（上交所/深交所）：传统大型企业，盈利要求高；创业板（深交所）：成长型企业，门槛相对低；科创板（上交所）：科技创新企业，允许亏损上市，注册制改革先试点。三个板块的估值体系和波动特征差异显著。",
        "content_en": "Main Board (SSE/SZSE): large traditional companies with strict profitability requirements. ChiNext (SZSE): growth companies with lower listing thresholds. STAR Market (SSE): innovation companies, allows unprofitable listings, pioneered registration-based reform. Each board has distinct valuation norms and volatility profiles.",
        "key_formula": "无单一公式。辨别方法：600xxx/601xxx/603xxx=上交所主板；000xxx/002xxx=深交所；300xxx=创业板；688xxx=科创板",
        "example": "600519 贵州茅台（上交所主板）；300750 宁德时代（创业板）；688981 中芯国际（科创板）。",
        "difficulty": "⭐",
        "tags": ["A股规则", "市场结构"],
    },
    {
        "topic": "沪深港通",
        "category": "A股规则",
        "content_zh": "沪港通（2014）和深港通（2016）允许境内外投资者通过相互连通的交易所跨市场买卖股票。南向资金（内地投资者买港股），北向资金（境外投资者买A股）。每日有额度限制（已大幅放宽）。",
        "content_en": "Shanghai-Hong Kong Connect (2014) and Shenzhen-Hong Kong Connect (2016) allow cross-market trading between mainland China, Hong Kong, and international investors. Southbound refers to mainland investors buying HK stocks; Northbound is the reverse. Daily quotas apply (significantly relaxed over time).",
        "key_formula": "互联互通每日额度：沪深港通单日净买入额不超过规定上限（已多次调整）",
        "example": "港股通（南向）让内地投资者可直接买腾讯（0700.HK）、阿里（9988.HK）等港股。",
        "difficulty": "⭐⭐",
        "tags": ["A股规则", "互联互通"],
    },
    {
        "topic": "除权除息",
        "category": "A股规则",
        "content_zh": "分红（派息）后股价按除息参考价下调，称为除息；送股（股本增加）后股价按比例下调，称为除权。除权除息后总市值不变，但股价降低了，容易被误判为股价"下跌"。实际上，复权后的价格才能真实反映收益。",
        "content_en": "When a company pays a cash dividend, the stock price is adjusted down by the dividend amount on the ex-dividend date. When bonus shares are issued, the price is proportionally reduced. Total market cap is unchanged. Adjusted (復權) prices properly reflect total returns for technical analysis.",
        "key_formula": "除息参考价 = (前收盘 − 每股现金红利) ÷ (1 + 送股比例)",
        "example": "股价 20 元，派息 0.5 元，送 10 股 → 除权除息参考价 = (20−0.5)÷(1+0.1) ≈ 17.7 元。",
        "difficulty": "⭐⭐",
        "tags": ["A股规则", "股息"],
    },
    # ── 投资理念类 ──────────────────────────────────────────────────────────
    {
        "topic": "分散投资原理",
        "category": "投资理念",
        "content_zh": "马科维茨现代组合理论证明：通过持有低相关性资产，可在不降低预期收益的前提下降低组合波动率。但过度分散（超过 20-30 只股票）带来的风险降低效果递减，且管理难度上升。适度集中在自己理解的领域更为明智。",
        "content_en": "Markowitz's Modern Portfolio Theory shows that holding uncorrelated assets reduces portfolio volatility without sacrificing expected returns. However, over-diversification beyond 20-30 stocks yields diminishing risk reduction and increased management complexity. Focused investing in areas of expertise often outperforms.",
        "key_formula": "组合波动率 < 加权平均个股波动率（当相关系数 < 1 时）",
        "example": "同时持有白酒、银行、医药、新能源各25%，比单一行业波动更小。",
        "difficulty": "⭐⭐",
        "tags": ["投资理念", "风险管理"],
    },
    {
        "topic": "复利效应",
        "category": "投资理念",
        "content_zh": "复利是"世界第八大奇迹"（爱因斯坦语）。每年将收益再投入本金，收益在下一期也产生收益，长期形成指数级增长。时间和收益率是复利的两个关键变量。年化15%坚持20年，本金增长约16倍。",
        "content_en": "Compound interest is the 'eighth wonder of the world' (attributed to Einstein). Reinvesting returns generates returns on returns, creating exponential growth over time. Time and rate of return are the two key variables. 15% annually for 20 years grows capital ~16x.",
        "key_formula": "终值 = 本金 × (1 + r)ⁿ；r = 年化收益率，n = 年数",
        "example": "10 万元，年化 15%，10 年后 ≈ 40.5 万；20 年后 ≈ 163 万。",
        "difficulty": "⭐",
        "tags": ["投资理念", "长期投资"],
    },
    {
        "topic": "价值投资 vs 成长投资",
        "category": "投资理念",
        "content_zh": "价值投资（巴菲特/格雷厄姆）：寻找被市场低估的优质企业，以低于内在价值的价格买入，等待价值回归。成长投资（费雪/林奇）：寻找高速成长的企业，愿意支付高估值换取未来高回报。两者并不对立，巴菲特晚期已融合两种风格。",
        "content_en": "Value investing (Buffett/Graham): buy quality businesses below intrinsic value, wait for the market to recognise true worth. Growth investing (Fisher/Lynch): pay a premium for companies with exceptional growth prospects. These styles are not mutually exclusive — later-era Buffett embraces both.",
        "key_formula": "格雷厄姆安全边际：只在价格远低于内在价值（通常>30%折扣）时买入",
        "example": "茅台在疫情低点跌至 900 元被认为是价值投资机会（后涨至 2600 元）。",
        "difficulty": "⭐⭐",
        "tags": ["投资理念", "投资策略"],
    },
    {
        "topic": "风险与收益的关系",
        "category": "投资理念",
        "content_zh": "资本资产定价模型（CAPM）指出，更高的预期收益必须以承担更高风险为代价。无风险收益率（国债）是基准，额外承担的市场风险（β）对应风险溢价。任何声称"高收益低风险"的投资都值得高度警惕。",
        "content_en": "CAPM establishes that higher expected returns require accepting higher risk. The risk-free rate (government bonds) is the baseline; additional market risk (β) commands a risk premium. Any investment claiming high return with low risk should be viewed with extreme scepticism.",
        "key_formula": "期望收益 = 无风险利率 + β × (市场收益 − 无风险利率)",
        "example": "若无风险利率 3%，市场收益 10%，β=1.5 → 期望收益 = 3% + 1.5×7% = 13.5%",
        "difficulty": "⭐⭐⭐",
        "tags": ["投资理念", "风险管理"],
    },
    {
        "topic": "贪婪恐惧指数",
        "category": "投资理念",
        "content_zh": "市场情绪在贪婪（过度乐观，导致高估）和恐惧（过度悲观，导致低估）之间摆动。巴菲特名言："别人贪婪时我恐惧，别人恐惧时我贪婪。" CNN编制的恐惧与贪婪指数（0-100）是常见情绪参考工具。",
        "content_en": "Market sentiment oscillates between greed (overoptimism causing overvaluation) and fear (excessive pessimism causing undervaluation). Buffett's famous maxim: 'Be fearful when others are greedy, and greedy when others are fearful.' CNN's Fear & Greed Index (0-100) is a popular sentiment gauge.",
        "key_formula": "无单一公式。综合波动率、动量、看跌/看涨期权比率等多个指标合成。",
        "example": "2020年3月疫情暴跌时恐惧指数触底，随后市场大幅反弹；2021年初指数过热。",
        "difficulty": "⭐⭐",
        "tags": ["投资理念", "市场情绪"],
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# Category → colour mapping (used by frontend)
# ─────────────────────────────────────────────────────────────────────────────
_CATEGORY_COLOR = {
    "估值":   "#8ab4f8",
    "技术分析": "#26a69a",
    "基本面":  "#ffa726",
    "宏观经济": "#c084fc",
    "A股规则": "#f06292",
    "投资理念": "#66bb6a",
}


@router.get("/today")
def knowledge_today():
    """Return the knowledge card of the day (deterministic by date seed)."""
    today = date.today()
    seed = int(today.strftime("%Y%m%d"))
    rng = random.Random(seed)
    item = rng.choice(_KB)

    return {
        "date":             today.isoformat(),
        "topic":            item["topic"],
        "category":         item["category"],
        "category_color":   _CATEGORY_COLOR.get(item["category"], "#8ab4f8"),
        "content_zh":       item["content_zh"],
        "content_en":       item["content_en"],
        "key_formula":      item["key_formula"],
        "example":          item["example"],
        "difficulty":       item["difficulty"],
        "tags":             item["tags"],
    }
