// ── Job Roles ─────────────────────────────────────────────────────────────────

export const ROLES = [
  {
    id: 'IBD',
    title: '投资银行部 (IBD)',
    titleEn: 'Investment Banking (IBD)',
    icon: '🏦',
    color: '#0ea5e9',
    tagline: '帮助企业完成融资与并购，赚顾问费，不直接持有资产风险',
    taglineEn: 'Advises companies on capital raises and M&A, earning advisory fees — no own-capital risk',
    description: 'IBD的本质是"帮助企业以最优条件筹集资金或出售/并购资产"。分析师每天的核心任务是搭建财务模型（Excel）和制作路演材料（PowerPoint），让客户的董事会或潜在投资者相信交易定价合理。以高强度著称——新人常常80-100小时/周，换来的是极其密集的金融技能积累和顶级的出路资源。',
    descriptionEn: 'IBD helps companies raise capital or buy/sell assets on the best possible terms. As an analyst, your daily core tasks are building financial models (Excel) and producing pitch materials (PowerPoint) that convince a board or investors that a deal\'s price is sound. Notorious for intensity — 80-100 hrs/week is common — but pays off with dense skill accumulation and premium exit opportunities.',
    coreScenario: '典型场景：客户是一家消费品公司，考虑战略性出售。你需要在48小时内：①搭建目标公司三表联动财务模型（基于近5年财报+管理层指引）；②拉取同行业5-8家可比公司交易倍数（Trading Comps）；③查找近3年行业并购先例（Precedent Transactions）；④将上述内容整合进40页Pitch Book初稿。MD会在最后一刻要求修改，速度和质量同样重要。',
    coreScenarioEn: 'Typical scenario: client is a consumer goods company exploring a strategic sale. Within 48 hours you must: ① build a three-statement financial model (5 years of financials + management guidance); ② pull trading multiples for 5-8 comparable companies; ③ find precedent M&A transactions in the sector over 3 years; ④ compile all of this into a 40-page pitch book draft. The MD will request last-minute changes — speed AND quality both matter.',
    skills: [
      '三表联动财务建模（Income Statement → Balance Sheet → Cash Flow Statement 循环链接，资产负债表必须自动平衡）',
      'DCF估值（5-7年自由现金流预测 + WACC计算 + 终值：Gordon增长法 vs. 退出倍数法两种方式交叉验证）',
      '可比公司分析（Trading Comps：从Capital IQ/Bloomberg筛选3-8家同行，计算EV/EBITDA、EV/Revenue、P/E倍数区间）',
      '先例交易分析（Precedent Transactions：Mergermarket/Bloomberg查找近3年同行业M&A，量化控制权溢价20-40%）',
      '增厚/摊薄分析（Accretion/Dilution Analysis：判断并购方案对买方EPS的影响，决定现金还是换股更优）',
      'LBO模型（评估PE买方收购价上限，反向推算5年IRR是否≥20%可行）',
      'Pitch Book / CIM制作（PowerPoint将财务模型浓缩成20-40页专业提案，图表设计要能经受客户追问）',
    ],
    skillsEn: [
      'Three-statement financial modeling (Income Statement → Balance Sheet → Cash Flow — balance sheet must auto-balance)',
      'DCF valuation (5-7 year FCF forecast + WACC + terminal value: Gordon Growth vs. Exit Multiple cross-validation)',
      'Comparable company analysis (Trading Comps: 3-8 peers via Capital IQ/Bloomberg, EV/EBITDA, EV/Revenue, P/E ranges)',
      'Precedent transaction analysis (Mergermarket/Bloomberg last 3 years M&A, quantify control premium 20-40%)',
      'Accretion/dilution analysis (EPS impact on buyer — determines whether cash or stock consideration is optimal)',
      'LBO modeling (reverse-engineer the max acquisition price PE can pay to hit a 20%+ IRR target)',
      'Pitch book / CIM (PowerPoint: distill model into 20-40 pages of professional pitch materials)',
    ],
    differentiators: [
      'vs. 股票研究（ER）：谁是你的客户决定一切。IBD代表企业利益（帮企业融资/出售），赚顾问费，倾向于为客户的定价辩护；ER代表机构投资者，可以独立给出"高估"评级。两者经常为同一笔交易站在谈判对立面。',
      'vs. 私募股权（PE）：IBD是中介顾问，赚费用不承担价格风险；PE是买方，拿自己管理的真实资金购买企业股权，持有3-7年赚资本利得。PE面试时优先从IBD分析师中招Associate，因为IBD建模能力和交易经验是PE入门的核心门槛。',
      'vs. 销售与交易（S&T）：IBD服务一级市场（新发行、私下并购），节奏以"项目"为单位（6-12个月一笔deal）；S&T服务二级市场，以每日开收盘为节奏，P&L每天实时可见。IBD几乎没有固定下班时间，S&T工作时间随市场明确开始和结束。',
    ],
    differentiatorsEn: [
      'vs. Equity Research (ER): IBD represents the company (helps it raise capital / sell), earns advisory fees, and argues for the client\'s valuation. ER represents institutional investors and can independently issue a "Sell" rating. The two often sit across the table in the same transaction.',
      'vs. Private Equity (PE): IBD is the intermediary, earning fees without holding equity risk. PE deploys real fund capital to buy company equity, holds 3-7 years, profits from appreciation. PE deliberately recruits IBD analysts as Associates because IBD\'s modeling skills and deal experience are the core entry prerequisites.',
      'vs. Sales & Trading (S&T): IBD serves the primary market (new issuances, negotiated M&A) — one deal can take 6-12 months. S&T serves the secondary market, P&L is visible every day. IBD analysts have essentially no fixed end time; S&T hours are defined by market open and close.',
    ],
    certs: [
      'CFA（进阶推荐）：IBD本身不强制CFA，但CFA覆盖的财报分析、估值和固收知识与日常建模高度契合。更重要的是，若计划从IBD转向PE/HF/AM，CFA在买方圈子是公认的"你不只会做模型"的专业信号。',
      'FINRA Series 7 & 63（美国合规硬性门槛）：美国监管要求任何参与证券销售推荐活动的人员必须持牌。没有Series 7，你在美国法律上无法向客户推荐证券产品（包括IPO路演介绍）。这不是加分项而是必须项。',
      '保荐代表人（中国必须晋升）：A股IPO和再融资需要持牌保代签字，对信息披露准确性承担连带责任。初级分析师阶段不需要，但晋升为保代是国内IBD职业的重要里程碑。',
    ],
    certsEn: [
      'CFA (recommended for progression): Not mandatory for IBD itself, but the curriculum — financial reporting, valuation, fixed income — maps directly to daily modeling work. More importantly, if you plan to move to PE/HF/AM, CFA signals to buy-side employers that you have structured finance knowledge beyond "Excel."',
      'FINRA Series 7 & 63 (hard regulatory requirement in US): Required for anyone "participating in securities sales activities." Without Series 7, you legally cannot participate in recommending securities to clients in the US. Not a bonus — a prerequisite.',
      'Sponsor Representative License (China career milestone): A-share IPOs require licensed sponsors to co-sign, accepting liability for disclosure accuracy. Not required at analyst level, but becoming a licensed sponsor is a key career milestone in China IBD.',
    ],
    entry: '顶尖高校本科（985/211国内，英美前20大学）金融/会计/经济/数学；GPA 3.5+（部分机构3.7+）；至少一段IBD/PE相关实习；校招Super-day包含笔试（会计+估值）+至少3轮面试；国内头部机构（中金/中信/高盛）offer接受率可能低于5%。现实：没有内推几乎过不了简历筛选。',
    entryEn: 'Target school undergraduate in finance/accounting/economics/math; GPA 3.5+ (some firms require 3.7+); at least one IBD/PE internship; super-day includes written test (accounting + valuation) + 3+ interview rounds; acceptance rate at top firms (CICC/CITIC/Goldman) can be below 5%. Reality: without a referral your resume may not pass the initial screen.',
    career: '分析师(2-3年) → Associate(通常MBA后重新进入或直接晋升) → VP → ED/Director → MD；常见出路：PE基金（最主流，通常在第2-3年跳，窗口期短）、对冲基金、公司战略/BD、创业',
    careerEn: 'Analyst (2-3y) → Associate (MBA re-entry or direct promotion) → VP → ED/Director → MD; common exits: PE funds (most common, jump in year 2-3 — window is short), hedge funds, corporate strategy/BD, entrepreneurship',
    salary: '国内顶级机构初级分析师：税前¥35–60万/年（含奖金）；国内中型机构：¥20–35万；美国大行：基础工资$110–130K，奖金可达50-100%基本工资',
    salaryEn: 'Top China firms junior analyst: RMB 350-600K/year (incl. bonus); mid-tier China: RMB 200-350K; US bulge bracket: $110-130K base, bonus 50-100% of base',
    disclaimer: '以上薪资区间为泛化估算，仅供参考，实际因公司/年份/个人情况差异较大。',
    disclaimerEn: 'Salary ranges above are generalized estimates for reference only; actual figures vary significantly by firm, year, and individual circumstances.',
    typicalDay: [
      '9:00 — 晨会：MD讲解3-4个当前活跃项目的最新进展和今日优先任务',
      '9:30-13:00 — 更新并购目标公司三表模型（昨晚客户发来Q3财报），调整收入假设，重跑敏感性分析，确认估值区间变化',
      '13:00-15:30 — 整理尽调清单进度，与法务对接文件，标记风险项',
      '15:30-18:00 — 制作Pitch Book新章节：行业竞争格局分析（Porter五力图表），搭建竞争对手比较表',
      '18:00-20:00 — VP发来修改意见："把收入增速改成保守/基准/乐观三情景"，更新后核对所有联动数字',
      '20:00+ — 等待MD对Pitch Book的反馈（通常晚上10-11点到）。若明天有客户会议，可能工作到凌晨',
    ],
    typicalDayEn: [
      '9:00 — Morning meeting: MD walks through 3-4 active deals and today\'s priorities',
      '9:30-13:00 — Update M&A target\'s three-statement model (client sent Q3 financials last night); adjust revenue assumptions, re-run sensitivity analysis, confirm valuation impact',
      '13:00-15:30 — Track due diligence checklist, coordinate with legal on documents, flag risk items',
      '15:30-18:00 — Build new pitch book chapter: industry competitive landscape (Porter\'s Five Forces chart), set up competitor comparison table',
      '18:00-20:00 — VP sends revision request: "model conservative/base/optimistic revenue scenarios" — update and cross-check all linked figures',
      '20:00+ — Waiting for MD\'s pitch book feedback (usually arrives 10-11pm). If client meeting is tomorrow, may work until 1-2am',
    ],
  },
  {
    id: 'EquityResearch',
    title: '股票研究 (Equity Research)',
    titleEn: 'Equity Research',
    icon: '🔍',
    color: '#8b5cf6',
    tagline: '持续深度覆盖上市公司，发布买/卖/持有评级和目标价',
    taglineEn: 'Deep ongoing coverage of listed companies, publishing Buy/Sell/Hold ratings with target prices',
    description: '研究分析师通常覆盖某一行业的8-15家上市公司，核心产出是研究报告（Research Note）。季报期间节奏最紧张——一家公司7点发财报，你要在9点半开市前更新完模型、写好快评（Flash Note）并给销售团队发简报。此外你需要有"非共识观点"（Non-consensus View）：与市场判断相反才会被机构客户重视。',
    descriptionEn: 'Research analysts typically cover 8-15 listed companies in one sector, core output being Research Notes. Earnings season is the most intense — a company releases earnings at 7am; you update the model, write a Flash Note, and brief the sales team before the 9:30am open. Beyond that, you need a "non-consensus view": your calls have value only when they diverge intelligently from market consensus.',
    coreScenario: '典型场景：你覆盖的消费品行业某龙头早上8:30发布季报，EPS比市场预期低15%。你需要在开市前（9:30）完成：①更新三表模型（找到差异来源：是收入不及预期，还是毛利率压缩？）；②写出1-2页快评（Flash Note，核心是解释"差异原因"和"是否影响长期逻辑"）；③给销售团队发简报（2-3句话，用他们转述给机构客户）；④决定是否下调目标价或投资评级，并附出完整逻辑。',
    coreScenarioEn: 'Typical scenario: the sector\'s leading company releases earnings at 8:30am, EPS 15% below consensus. Before market open (9:30am) you must: ① update the three-statement model (find the source of the miss: was it revenue shortfall or margin compression?); ② write a 1-2 page Flash Note (core: explain the "reason for the miss" and "whether it changes the long-term thesis"); ③ brief the sales team (2-3 sentences they can relay to institutional clients); ④ decide whether to cut target price or rating, with complete logic attached.',
    skills: [
      '行业深度研究（追踪产业链上下游、监测渠道数据、管理层访谈——比IBD在同一行业的了解深10倍）',
      '财务建模（DCF + EV/EBITDA相对估值）：精度要求略低于IBD但逻辑一致性要更高（因为你会被机构客户反复追问假设）',
      'Research Note写作（从数据到投资逻辑的转化：能在1页内说清楚"买入理由+主要风险+目标价依据"）',
      'Capital IQ / Bloomberg数据库精通（拉取财务数据、估值倍数历史、共识预测对比）',
      '草根调查（Channel Check）：通过供应商、经销商、终端消费者获取一手数据，形成领先于财报的判断',
      '投资逻辑构建（从行业驱动因素→个股竞争优势→催化剂时间表→上下行风险，形成完整投资框架）',
    ],
    skillsEn: [
      'Deep industry research (tracking supply chain, monitoring channel data, management interviews — understanding the industry 10x deeper than IBD)',
      'Financial modeling (DCF + EV/EBITDA relative valuation): slightly less precision than IBD but logic consistency is higher (institutional clients will probe every assumption)',
      'Research note writing (converting data to investment thesis: explain "buy thesis + key risks + target price rationale" within 1 page)',
      'Capital IQ / Bloomberg proficiency (pull financials, historical valuation multiples, consensus estimate comparisons)',
      'Channel checks: get primary data from suppliers, distributors, end consumers to form judgments ahead of reported financials',
      'Investment thesis construction (sector drivers → company competitive advantage → catalyst timeline → upside/downside risks)',
    ],
    differentiators: [
      'vs. 投资银行（IBD）：最根本的区别是"谁是你的客户"。ER代表机构投资者（告诉基金经理这只股票值不值得买），可以独立给出"卖出"评级；IBD代表企业（帮企业融资），基本不会公开质疑自己的客户。两者分析同一家公司可能得出完全相反的结论。',
      'vs. 资产管理（AM）：ER是"卖方研究员"（Sell-side），你的报告是写给买方基金经理看的——你提供分析，决策由别人做；AM是"买方研究员/基金经理"（Buy-side），你直接负责资金的盈亏，研究结论必须转化为真实持仓决策。ER写"建议买入"但不用承担实际亏损风险，AM必须承担。',
      'vs. 量化（Quant）：ER主要依赖定性分析+财务建模（行业逻辑、管理层判断），Quant主要依赖统计方法+大样本数据（跨行业的系统性规律）。ER分析师通常对单个公司了解极深但覆盖公司数量少（8-15家），Quant研究员覆盖全市场但对单公司基本面了解很浅。',
    ],
    differentiatorsEn: [
      'vs. Investment Banking (IBD): The fundamental difference is "who is your client." ER represents institutional investors (tells fund managers whether a stock is worth buying) and can independently issue a "Sell" rating. IBD represents the company and essentially never publicly questions its own clients. Both analyze the same company but can reach opposite conclusions.',
      'vs. Asset Management (AM): ER is "sell-side" — you provide analysis and recommendations, but the investment decision and P&L responsibility lies with the fund manager. AM is "buy-side" — your research must convert directly into real position decisions and you bear the P&L consequences. ER can say "Buy" without ever being accountable for the actual outcome.',
      'vs. Quant: ER relies primarily on qualitative analysis + financial modeling (industry logic, management quality), while Quant relies on statistical methods + large-sample data (systematic cross-sector patterns). ER analysts know individual companies extremely deeply but cover few (8-15); Quant researchers cover the whole market but have shallow fundamental knowledge of individual companies.',
    ],
    certs: [
      'CFA（强烈推荐，行业几乎标配）：CFA Level 2的财报分析和权益估值模块就是ER日常工作的理论教科书；Level 3的组合管理知识帮助你理解机构客户的思维框架。持有CFA的分析师被机构客户视为"专业性更高"，研报可信度更强。',
      'FRM（进阶选项）：如果你覆盖的是金融行业股票（银行/保险/资产管理公司），FRM对理解这些公司的资产负债表风险和监管逻辑极有帮助。',
    ],
    certsEn: [
      'CFA (strongly recommended — near industry standard): CFA Level 2 financial reporting and equity valuation is essentially the textbook for ER daily work; Level 3 portfolio management helps you understand how your institutional clients think. CFA holders are seen as more credible by institutional clients.',
      'FRM (advanced option): If you cover financial sector stocks (banks/insurance/asset managers), FRM is very useful for understanding their balance sheet risk and regulatory framework.',
    ],
    entry: '金融/经济/会计/相关行业背景本科或硕士；行业研究经验（在校做过某行业深度研究）加分；Bloomberg实操能力；部分顶级卖方要求MBA；没有相关背景可考虑从行业内部转来（如消费品公司的市场分析师转做消费品研究）',
    entryEn: 'Finance/economics/accounting or relevant sector background undergraduate or master; prior industry research experience a plus; Bloomberg proficiency required; some top sell-side firms require MBA; consider lateral entry from industry (e.g., consumer company analyst transferring to consumer research)',
    career: '研究助理(Associate) → 初级分析师 → 高级分析师 → 首席分析师（明星分析师进New Fortune/Thomson Reuters排名）；出路：买方基金（对冲基金/公募基金），薪资天花板大幅提升',
    careerEn: 'Research Associate → Junior Analyst → Senior Analyst → Lead Analyst (star analysts rank in New Fortune/Thomson Reuters); exits: buy-side funds (hedge funds/mutual funds), dramatically higher compensation ceiling',
    salary: '国内券商初级分析师：¥20–40万；明星分析师（新财富上榜）：¥100万+；美国卖方研究：$80–120K（初级），明星分析师$500K+',
    salaryEn: 'China broker junior analyst: RMB 200-400K; star analysts (New Fortune ranked): RMB 1M+; US sell-side: $80-120K (junior), star analysts $500K+',
    disclaimer: '以上薪资区间为泛化估算，仅供参考，实际因公司/年份/个人情况差异较大。',
    disclaimerEn: 'Salary ranges above are generalized estimates for reference only; actual figures vary significantly by firm, year, and individual circumstances.',
    typicalDay: [
      '7:00 — 浏览境外市场隔夜动态（港股/美股）、行业新闻、被覆盖公司的公告',
      '8:30-9:30 — 季报期：更新财务模型，写Flash Note快评（1-2页）',
      '9:30-11:30 — 开市期间：配合销售团队接待机构客户电话，解释最新研究观点',
      '11:30-15:00 — 调研：实地走访渠道（超市/经销商），或电话访谈上下游供应商',
      '15:00-18:00 — 撰写深度报告（Deep Dive）：新催化剂驱动的行业洞察，或季报后更新完整的投资逻辑',
      '18:00+ — 整理投资组合经理的反馈，更新共识预测偏差追踪表',
    ],
    typicalDayEn: [
      '7:00 — Scan overnight HK/US market moves, industry news, covered company announcements',
      '8:30-9:30 — Earnings season: update financial models, write Flash Note (1-2 pages)',
      '9:30-11:30 — Market hours: join sales team on institutional client calls, explain latest research views',
      '11:30-15:00 — Research: field visits to retail channels/distributors, or call supply chain contacts',
      '15:00-18:00 — Write deep-dive report: industry insight driven by a new catalyst, or post-earnings full thesis update',
      '18:00+ — Process portfolio manager feedback, update consensus estimate deviation tracker',
    ],
  },
  {
    id: 'ST',
    title: '销售与交易 (Sales & Trading)',
    titleEn: 'Sales & Trading',
    icon: '📈',
    color: '#26a69a',
    tagline: '市场实时博弈——P&L每天可见，节奏由市场开收盘决定',
    taglineEn: 'Real-time market execution — P&L is visible every day, pace dictated by market open and close',
    description: 'Sales负责与机构客户沟通，理解其交易需求并推荐策略；Trading负责在市场中实际执行交易、管理风险敞口（Greeks）。这个岗位要求在不完整信息下毫秒级快速决策，P&L每天实时可见——这意味着你今天赚了多少亏了多少，整个交易台都知道。',
    descriptionEn: 'Sales communicates with institutional clients to understand trading needs and pitch strategies; Trading executes positions and manages risk exposures (Greeks). This role demands rapid decisions (second to millisecond) under incomplete information, with P&L visible to the entire desk every day — there\'s nowhere to hide.',
    coreScenario: '典型场景（交易员）：早上7:45，你管理的利率衍生品台账面上有一笔利率互换（IRS）仓位，隔夜美联储官员释放鹰派信号。你需要：①估算Delta暴露变化（利率上行25bps对你台面的P&L影响）；②联系销售同事确认大客户今日方向；③在开市前设定止损线（日内亏损超过$X则自动平仓）；④市场开盘后实时对客户询价，每次报价同时考虑客户需求和自身风险对冲成本。',
    coreScenarioEn: 'Typical scenario (trader): 7:45am, you have an interest rate swap position on your book; overnight a Fed official made hawkish comments. You must: ① estimate delta exposure change (impact of a 25bps rate move on your desk\'s P&L); ② check with sales colleagues on large clients\' expected direction today; ③ set stop-loss before open (auto-flatten if intraday loss exceeds $X); ④ quote clients in real time after open, simultaneously weighing client demand and your own hedging cost on every quote.',
    skills: [
      '市场微观结构（Bid-Ask Spread管理、市场深度分析、成交量加权平均价VWAP执行）',
      '衍生品定价基础（Black-Scholes期权定价、利率互换的NPV计算、信用违约互换CDS定价逻辑）',
      'Greeks管理（Delta对冲—通过买卖标的使组合Delta接近0；Gamma暴露管理—ATM期权Gamma最高）',
      '产品知识（至少精通一个资产类别：股票/利率/外汇/大宗商品/信用，了解其市场结构和定价逻辑）',
      '风险意识（每个仓位都要知道最大可能亏损是多少，在哪个价位止损，而不是"等它涨回来"）',
      '压力下快速决策（盘中不允许"再想想"，每个报价窗口通常只有几秒）',
    ],
    skillsEn: [
      'Market microstructure (bid-ask spread management, market depth analysis, VWAP execution)',
      'Derivatives pricing basics (Black-Scholes, NPV of interest rate swaps, CDS pricing logic)',
      'Greeks management (delta hedging — buy/sell underlying to keep delta near zero; gamma exposure — highest at ATM)',
      'Product knowledge (must master at least one asset class: equities/rates/FX/commodities/credit — understand its market structure and pricing)',
      'Risk awareness (for every position, know the maximum possible loss and where to stop out — never "wait for it to recover")',
      'Rapid decision-making under pressure (no time to "think more" during market hours — quote windows are often seconds)',
    ],
    differentiators: [
      'vs. IBD：IBD服务一级市场（新发行证券/私下并购），P&L以"是否赢得交易并成功执行"来衡量，节奏以项目为单位（6-12个月）；S&T服务二级市场，P&L每天实时可见，每天都是"考试"。IBD失败了最多是这笔交易丢了，S&T如果风险管理失败可能一天亏掉全季度利润。',
      'vs. 量化（Quant）：S&T交易员的工作是手动/半自动执行交易、管理风险仓位，依赖市场直觉+规则；Quant开发的是完全系统化的算法策略（代码生成信号→自动执行）。两者在顶级机构界限模糊（量化交易台），但传统S&T更强调人工判断，Quant更强调模型和数学严谨性。',
      'vs. 资产管理（AM）：S&T的核心是"执行"（以最优价格在市场中完成客户/自营交易），是AM的服务提供方；AM的核心是"决策"（决定买什么、持有多久）。S&T的客户就包括AM公司，前者为后者提供流动性和执行服务。',
    ],
    differentiatorsEn: [
      'vs. IBD: IBD serves the primary market (new issuances, negotiated M&A), P&L measured by "did we win and execute the deal," pace is project-based (6-12 months). S&T P&L is visible every day — every day is an exam. IBD\'s worst case is losing a deal; S&T\'s worst case is a single bad day wiping out a quarter\'s profits.',
      'vs. Quant: S&T traders execute trades manually/semi-manually and manage risk positions, relying on market intuition + rules. Quant develops fully systematic algorithmic strategies (code generates signals → auto-executes). The line blurs at top firms, but traditional S&T emphasizes human judgment; Quant emphasizes mathematical rigor.',
      'vs. Asset Management (AM): S&T\'s core is "execution" (completing trades at best price) — S&T is AM\'s service provider. AM\'s core is "decision-making" (what to buy and how long to hold). AM firms are S&T\'s clients — S&T provides liquidity and execution services to AM.',
    ],
    certs: [
      'FINRA Series 7 & 63（美国合规必须）：与IBD相同，美国监管要求持牌。Series 57（证券交易员牌照）在S&T岗位比Series 7更直接相关，专门针对二级市场交易活动。',
      'CFA（S&T中不是核心要求，但Level 1/2的衍生品和固收模块有直接用处）：如果你做利率或信用产品，CFA的固定收益定价知识与日常估值直接相关；如果你做股票，CFA的技术含量对纯执行类工作帮助有限。',
      '期货从业资格（国内合规必须）：在国内做期货/衍生品相关S&T业务需要取得期货从业资格，类似美国的Series牌照，是参与期货交易的合规门槛。',
    ],
    certsEn: [
      'FINRA Series 7 & 63 (mandatory in US): Same as IBD. Series 57 (Securities Trader license) is more directly relevant for S&T specifically, covering secondary market trading activities.',
      'CFA (not core for S&T, but Level 1/2 derivatives and fixed income modules are directly useful): Relevant if you trade rate or credit products; less relevant for pure equity execution roles.',
      'Futures Practitioner License (mandatory in China): Required for futures/derivatives-related S&T business in China — the regulatory equivalent of the US Series licenses.',
    ],
    entry: '数学/物理/CS/统计/金融本科；强烈的数字敏感度（面试可能现场做心算）；心理素质稳定（面试官会故意施压测试）；校内模拟交易、量化竞赛经历加分；部分机构有数学/逻辑测试（类似对冲基金数学筛选）',
    entryEn: 'Math/physics/CS/statistics/finance undergraduate; strong numerics (interviews may include mental math); emotional stability under pressure (interviewers will deliberately stress-test you); simulated trading or quant competition experience a plus; some firms include math/logic tests',
    career: '初级交易员/销售助理 → 高级交易员 → 交易台主管 → 交易部门负责人；出路：对冲基金（最主流）、自营交易公司（Prop Firm，如Jump/Citadel Securities）',
    careerEn: 'Junior Trader/Sales Associate → Senior Trader → Head of Desk → Head of Trading; exits: hedge funds (most common), prop trading firms (Jump/Citadel Securities)',
    salary: '国内证券公司初级：¥20–40万；美国大行初级：$85–130K基础工资，奖金与台面P&L强相关；顶级做市商/自营台面奖金可远超基础工资',
    salaryEn: 'China junior: RMB 200-400K; US bulge bracket junior: $85-130K base, bonus highly correlated with desk P&L; top market-making/prop desks can pay multiples of base',
    disclaimer: '以上薪资区间为泛化估算，仅供参考，实际因公司/年份/个人情况差异较大。',
    disclaimerEn: 'Salary ranges above are generalized estimates for reference only; actual figures vary significantly by firm, year, and individual circumstances.',
    typicalDay: [
      '7:00 — 查看隔夜市场（美股/欧股/亚股），标注对今日持仓有影响的宏观事件',
      '7:30-9:30 — 台面晨会：回顾昨日P&L，讨论今日重点（经济数据发布时间、重大新闻），确认每人的风险限额',
      '9:30-11:30 — 市场开盘，对客户询价流水作业，管理实时Delta暴露',
      '11:30-13:00 — 整理上午P&L归因（"哪笔仓位贡献了多少"），与销售沟通大客户动向',
      '13:00-15:00 — 午后流动性下降时段，逐步调整仓位，准备下午收盘前的对冲',
      '15:00-收盘 — 收盘前流动性恢复，处理大宗交易；收盘后整理全日P&L，上报风险敞口',
    ],
    typicalDayEn: [
      '7:00 — Review overnight markets (US/EU/Asia), flag macro events impacting today\'s positions',
      '7:30-9:30 — Desk morning meeting: review yesterday\'s P&L, discuss key events (data releases, major news), confirm risk limits',
      '9:30-11:30 — Market open: quote clients in rapid succession, manage real-time delta exposure',
      '11:30-13:00 — Review morning P&L attribution ("which position contributed how much"), coordinate with sales on large client flows',
      '13:00-15:00 — Lower-liquidity afternoon session: gradually adjust positions, prepare hedges before close',
      '15:00-close — Pre-close liquidity pickup, handle block trades; after close compile full-day P&L and report risk exposures',
    ],
  },
  {
    id: 'AM',
    title: '资产管理 (Asset Management)',
    titleEn: 'Asset Management',
    icon: '💼',
    color: '#f6c90e',
    tagline: '管理真实资金，为机构或个人投资者实现长期风险调整后收益',
    taglineEn: 'Manage real capital to deliver long-term risk-adjusted returns for institutional or individual investors',
    description: '资产管理（公募基金/私募基金/养老金）是金融行业的"买方"。与卖方不同，你负责最终投资决策，研究结论必须转化为真实持仓，亏损由你和持有人共同承担。工作分工：组合经理（PM）做最终决策，研究员提供标的深挖，销售负责AUM扩张。核心压力是长期业绩—— 一旦连续跑输基准，将面临赎回压力。',
    descriptionEn: 'Asset management (mutual funds/private funds/pensions) is the buy-side of finance. Unlike sell-side, you make the final investment decision — research must convert to real positions and losses are borne by you and your investors. Roles: Portfolio Manager (PM) makes final calls, analysts do deep research, sales expands AUM. Core pressure is long-term performance — consecutive underperformance leads to redemption pressure.',
    coreScenario: '典型场景：你管理一只50亿人民币的消费品主题基金，某季报季，你判断某龙头公司Q2收入增速将高于市场预期5个百分点（基于你对其渠道商补货数据的追踪）。你需要决定：①财报前是否建仓（存在信息误判风险）；②仓位规模（风险预算限制每只个股仓位不超过8%）；③如果判断正确但股价已提前上涨，如何评估"Upside是否仍然足够"；④若本季度组合落后沪深300指数3个百分点，如何向持有人和销售团队出具有说服力的归因报告。',
    coreScenarioEn: 'Typical scenario: you manage a RMB 5B consumer theme fund. You believe a leading company\'s Q2 revenue growth will beat consensus by 5pp (based on your channel inventory tracking). You must decide: ① whether to build a position before earnings (risk of being wrong); ② position size (risk budget limits any single stock to 8% of portfolio); ③ if the thesis is right but the stock already ran, evaluate "is the remaining upside still sufficient?"; ④ if the portfolio trails CSI 300 by 3pp this quarter, prepare a convincing attribution report for investors and sales.',
    skills: [
      '投资组合构建（从选股→仓位sizing→行业集中度管理→风险预算分配，形成有内在逻辑的组合）',
      '因子分析（价值/成长/动量/质量因子的历史有效性，以及在不同市场周期下的失效场景）',
      '组合业绩归因（Brinson归因模型：区分资产配置贡献vs个股选择贡献，给出有说服力的业绩解释）',
      '宏观分析（货币政策、利率周期、汇率对不同资产类别的传导路径）',
      'Bloomberg/Wind精通（拉取行情数据、共识预测、基金持仓比较、估值历史分位）',
      '客户沟通（定期向持有人/LP解释投资策略和组合变化，把复杂的金融逻辑转化为非专业人士能理解的语言）',
    ],
    skillsEn: [
      'Portfolio construction (stock selection → position sizing → sector concentration management → risk budget allocation — a coherent portfolio)',
      'Factor analysis (value/growth/momentum/quality factors: historical effectiveness and failure modes across different market cycles)',
      'Portfolio performance attribution (Brinson model: separate asset allocation contribution vs. stock selection contribution — give a convincing performance explanation)',
      'Macro analysis (monetary policy, rate cycle, FX transmission to different asset classes)',
      'Bloomberg/Wind proficiency (pull price data, consensus estimates, fund holding comparisons, valuation percentile history)',
      'Client communication (explain investment strategy and portfolio changes to investors/LPs in language non-professionals can understand)',
    ],
    differentiators: [
      'vs. 股票研究（ER）：ER是卖方——你提供分析建议，决策由别人做；AM是买方——你不仅要有观点，还要拿真实资金下注，亏了要向持有人负责。ER分析师可以写"买入"研报然后对其后续表现不负责；AM组合经理必须承担持仓结果。',
      'vs. 私募股权（PE）：AM主要投资于流动性好的公开市场（股票/债券），可以随时买卖；PE投资的是非上市公司股权，流动性极差，持有周期3-7年，期间无法轻易退出。AM的风险是"每天波动"（市场价格风险），PE的风险是"长期判断失误"（企业基本面风险）。',
      'vs. 量化（Quant）：AM通常是"主动管理"（Active Management）：研究员通过基本面分析精选个股，依赖人工判断形成超额收益（Alpha）；Quant是系统化的"因子投资"：用数学模型跨市场寻找规律，不依赖对单公司的深度了解。两者在大型机构内常常同时存在并相互竞争AUM。',
    ],
    differentiatorsEn: [
      'vs. Equity Research (ER): ER is sell-side — you provide analysis, others make the decision. AM is buy-side — you must put real money behind your views and be accountable to investors if you\'re wrong. ER analysts can write a "Buy" and not be held responsible; AM portfolio managers bear the P&L consequences.',
      'vs. Private Equity (PE): AM primarily invests in liquid public markets (stocks/bonds), tradeable at any time. PE invests in unlisted company equity — illiquid, 3-7 year hold periods, cannot easily exit. AM risk is "daily mark-to-market volatility"; PE risk is "long-term fundamental misjudgment."',
      'vs. Quant: AM is typically "active management" — analysts use fundamental analysis to select individual stocks, relying on human judgment for alpha. Quant uses mathematical models to find systematic cross-market patterns, without deep knowledge of individual companies. Both coexist and compete for AUM within large institutions.',
    ],
    certs: [
      'CFA（几乎必备，尤其Level 3）：CFA Level 3的核心内容是"投资组合管理"——资产配置、风险管理、绩效归因、行为金融学，与AM日常工作内容重叠度超过50%。这是CFA各级别中对AM岗位直接适用性最高的阶段。持有CFA是AM招聘中的标准背景要求。',
      '基金从业资格（国内合规必须）：在国内参与公募/私募基金投资管理活动的人员必须通过基金从业资格考试。这是参与买方资产管理业务的合规入门门槛。',
      'FRM（进阶选项）：如果你专注于固定收益或混合类基金，FRM的利率风险和信用风险模块对日常组合风险管理有直接帮助。',
    ],
    certsEn: [
      'CFA (near-essential, especially Level 3): CFA Level 3 covers portfolio management, asset allocation, risk management, performance attribution, and behavioral finance — overlapping 50%+ with AM daily work. This is the most directly applicable CFA level for AM roles. CFA is a standard background requirement in AM hiring.',
      'Fund Practitioner License (mandatory in China): Required for anyone involved in public/private fund investment management activities in China — the regulatory entry threshold for buy-side asset management.',
      'FRM (advanced option): If you focus on fixed income or multi-asset funds, FRM\'s interest rate risk and credit risk modules are directly useful for portfolio risk management.',
    ],
    entry: '金融/经济/理工科本科或硕士；CFA Level 1/2进阶必要；部分机构要求先做1-2年卖方研究员再跳买方；大型公募基金春季/秋季校招；私募基金通常通过猎头定向招募经验人士',
    entryEn: 'Finance/economics/STEM undergrad or master; CFA Level 1/2 increasingly required; some firms prefer 1-2 years sell-side research experience first; large public funds recruit on campus; private funds typically source experienced candidates through headhunters',
    career: '研究助理 → 行业研究员 → 高级研究员 → 基金经理助理 → 基金经理（PM）→ 明星基金经理；或横向：PE/对冲基金',
    careerEn: 'Research Associate → Sector Analyst → Senior Analyst → Junior PM → Portfolio Manager → Star PM; or lateral: PE / hedge funds',
    salary: '国内公募基金初级研究员：¥20–35万；明星基金经理：百万至千万级别（含业绩提成）；美国共同基金初级：$75–110K',
    salaryEn: 'China public fund junior analyst: RMB 200-350K; star portfolio managers: RMB millions to tens of millions (including performance fees); US mutual fund junior: $75-110K',
    disclaimer: '以上薪资区间为泛化估算，仅供参考，实际因公司/年份/个人情况差异较大。',
    disclaimerEn: 'Salary ranges above are generalized estimates for reference only; actual figures vary significantly by firm, year, and individual circumstances.',
    typicalDay: [
      '8:30 — 晨会：讨论隔夜市场动态，各研究员分享覆盖标的最新信息',
      '9:30-11:30 — 跟踪持仓标的实时表现，若有重大新闻或超预期数据，判断是否需要调仓',
      '11:30-13:00 — 调研：与被覆盖公司IR（投资者关系）或管理层电话会议',
      '13:00-15:00 — 深度研究：更新财务模型，分析新标的的买入逻辑，准备下周的投资决策备忘录',
      '15:00-17:00 — 组合归因分析：哪些持仓今日贡献了超额收益/拖累了组合，背后原因是什么',
      '17:00+ — 整理销售团队反馈（持有人问了哪些问题），更新基金月报数据',
    ],
    typicalDayEn: [
      '8:30 — Morning meeting: discuss overnight developments, each analyst shares updates on covered companies',
      '9:30-11:30 — Monitor portfolio positions\' real-time performance; if major news or earnings surprise, evaluate whether to trade',
      '11:30-13:00 — Research: conference calls with covered company IR or management',
      '13:00-15:00 — Deep research: update financial models, build investment case for new ideas, prepare investment decision memo for next week',
      '15:00-17:00 — Portfolio attribution analysis: which holdings generated/dragged alpha today, and why',
      '17:00+ — Process sales team feedback (what questions did investors ask), update fund monthly report data',
    ],
  },
  {
    id: 'PE',
    title: '私募股权 (Private Equity)',
    titleEn: 'Private Equity',
    icon: '🦅',
    color: '#ef5350',
    tagline: '用基金资金收购企业股权，通过价值创造实现超额回报后退出',
    taglineEn: 'Deploy fund capital to acquire company equity, create value, then exit for outsized returns',
    description: 'PE基金通过杠杆收购（LBO）或成长型投资持有私有企业股权，3-7年内通过改善运营、战略并购或IPO退出。PE分析师建模的目的是"决定是否真实投入数亿资金"，精度要求远高于IBD。招聘极其竞争激烈——国内头部机构（鼎晖/高瓴/红杉）通常优先从顶级IBD分析师中直接招募。',
    descriptionEn: 'PE funds acquire stakes in private companies through LBOs or growth equity, creating value over 3-7 years via operational improvement, add-on acquisitions, or IPO exits. PE modeling determines whether to deploy hundreds of millions — precision requirements far exceed IBD. Hiring is intensely competitive; top China PE funds (Hillhouse/Sequoia/CDH) typically recruit directly from top IBD analysts.',
    coreScenario: '典型场景：评估一家年EBITDA 8000万元的食品制造企业（8亿元收购价，10x EBITDA）。你作为助理在两周内需要：①搭建LBO模型（50%债务杠杆，测算5年IRR是否≥20%）；②完成行业竞争格局分析（4-6页行业摘要）；③初步尽调清单（财务/法律/运营三个维度各10-15项）；④撰写投资委员会备忘录初稿（IC Memo，约15-20页），呈现投资逻辑、风险和退出路径，并统筹律所、会计师事务所、行业顾问的工作进度。',
    coreScenarioEn: 'Typical scenario: evaluate a food manufacturer with RMB 80M EBITDA (RMB 800M acquisition price, 10x EBITDA). As an associate, within two weeks you must: ① build an LBO model (50% debt leverage, verify whether 5-year IRR ≥20%); ② complete an industry competitive analysis (4-6 page industry summary); ③ initial due diligence checklist (10-15 items each across financial/legal/operational dimensions); ④ draft an investment committee memo (IC Memo, ~15-20 pages) covering investment thesis, risks, and exit paths — while coordinating law firms, accounting firms, and industry consultants.',
    skills: [
      'LBO建模（核心：搭建资本结构→债务偿还计划→退出倍数敏感性→反推最大可接受收购价，使IRR目标可达）',
      '运营价值创造分析（不只是财务建模，要分析"持有期间如何提升EBITDA"：收入增长路径/成本削减机会/并购整合潜力）',
      '尽职调查（DD）统筹（财务DD：识别盈余质量/一次性项目；法律DD：合同风险/或有负债；运营DD：管理团队评估/市场份额趋势）',
      '投资委员会备忘录（IC Memo）写作（用15-20页说清楚：为什么投/为什么是现在/为什么这个价格/主要风险如何缓解/退出路径和时间表）',
      '行业竞争格局分析（Porter五力+行业增长驱动因素+竞争对手基准分析，支撑投资假设的合理性）',
      'IRR/MOIC计算（MOIC=退出权益/初始股权投入；IRR是使所有现金流NPV=0的折现率，通常目标5年20%+IRR / 2-3x MOIC）',
    ],
    skillsEn: [
      'LBO modeling (core: build capital structure → debt repayment schedule → exit multiple sensitivity → reverse-engineer maximum acquisition price to hit IRR target)',
      'Operational value creation analysis (not just modeling — analyze "how to grow EBITDA during hold period": revenue growth path / cost reduction opportunities / M&A integration potential)',
      'Due diligence (DD) coordination (Financial DD: earnings quality/one-time items; Legal DD: contract risks/contingent liabilities; Operational DD: management team assessment/market share trends)',
      'Investment committee memo (IC Memo) writing (15-20 pages explaining: why invest / why now / why this price / how to mitigate key risks / exit paths and timeline)',
      'Industry competitive analysis (Porter Five Forces + growth drivers + competitor benchmarking to support investment assumptions)',
      'IRR/MOIC calculation (MOIC = exit equity / initial equity invested; IRR = discount rate making all cash flows NPV=0; typical target: 5-year 20%+ IRR / 2-3x MOIC)',
    ],
    differentiators: [
      'vs. IBD：IBD是中介顾问，赚顾问费不承担价格风险——deal结束关系基本结束；PE是买方，拿真实资金购买企业股权，持有3-7年，期间需要深度参与被投企业的战略改善（有时直接派人进驻董事会）。PE对模型精度的要求更高，因为错误假设直接导致真实资金损失。',
      'vs. 资产管理（AM）：PE投资非上市公司，流动性极差——一旦投入通常无法在3-5年内退出；AM投资上市公司，可随时买卖。PE的价值创造是主动的（直接介入企业运营），AM的价值来源是被动的（市场重新定价）。PE按基金周期（通常10年）运作，AM持续管理AUM无固定周期。',
      'vs. 量化（Quant）：PE是"深度而窄"的研究（对少数几家公司了解极深），Quant是"广度而浅"的数据驱动（跨市场全覆盖但不做公司深度研究）。PE的投资期以年计，Quant策略的持仓周期从毫秒到几个月不等。',
    ],
    differentiatorsEn: [
      'vs. IBD: IBD is the intermediary, earning fees without holding equity risk — the relationship largely ends when the deal closes. PE is the buyer, deploying real fund capital to acquire company equity, holding 3-7 years, and actively participating in the investee\'s strategic improvement (often placing board directors). PE modeling precision requirements are much higher because wrong assumptions mean real money losses.',
      'vs. Asset Management (AM): PE invests in unlisted companies — once deployed, you typically cannot exit for 3-5 years. AM invests in listed companies and can trade anytime. PE value creation is active (directly intervening in company operations); AM value comes from market repricing. PE operates on fund cycles (typically 10 years); AM continuously manages AUM with no fixed cycle.',
      'vs. Quant: PE is "deep and narrow" research (extremely deep understanding of a few companies). Quant is "broad and data-driven" (market-wide coverage but no deep fundamental research). PE hold periods are measured in years; Quant strategy holding periods range from milliseconds to months.',
    ],
    certs: [
      'CFA（进阶推荐）：PE不强制CFA，但CFA的LBO和私募股权投资模块（Level 3新增内容）与日常工作直接相关。若计划长期留在买方（而非转去创业），CFA是维持专业信誉的有效方式。',
      'MBA（中期晋升重要路径）：顶级PE（KKR/黑石/高瓴）通常要求Associate晋升VP前完成顶级MBA（Harvard/Wharton/Stanford），这既是培训也是筛选机制。提前规划MBA申请是PE职业路径的重要一步。',
    ],
    certsEn: [
      'CFA (recommended for progression): Not mandatory for PE, but CFA\'s LBO and private equity investment modules (Level 3 addition) are directly relevant. If you plan to stay buy-side long-term (rather than founding a company), CFA is an effective way to maintain professional credibility.',
      'MBA (important mid-career progression path): Top PE firms (KKR/Blackstone/Hillhouse) typically require Associates to complete a top MBA (Harvard/Wharton/Stanford) before promotion to VP — both training and a selection mechanism. Planning for MBA applications is an important step in the PE career path.',
    ],
    entry: '通常从IBD分析师第2-3年转岗（建模测试+案例分析是核心门槛）；极少直接招本科；国内头部PE（高瓴/鼎晖/红杉）通过猎头进行定向招募，不公开发布JD；建模测试通常要求在限定时间（3小时）内搭建完整LBO模型',
    entryEn: 'Typically from IBD analysts in year 2-3 (modeling test + case study are the core hurdles); rarely hire undergrads directly; top China PE (Hillhouse/CDH/Sequoia) recruit through headhunters without public job postings; modeling tests typically require building a complete LBO in 3 hours',
    career: '助理(Associate，2-3年) → 高级助理/副总裁(VP) → 合伙人(Partner)；部分回读MBA后重新进入；少数晋升为独立GP/创办基金',
    careerEn: 'Associate (2-3y) → Senior Associate/VP → Partner; some exit for MBA then re-enter; a few advance to become independent GPs / found their own funds',
    salary: '国内头部机构初级助理：税前¥40–100万（含业绩分成预期）；美国中型PE：$150–200K基础工资；Carry（已实现的附带权益）是长期最重要的收入',
    salaryEn: 'Top China PE junior associate: RMB 400K-1M (including expected carry); US mid-market PE: $150-200K base; Carried interest (realized carry) is the most important long-term income component',
    disclaimer: '以上薪资区间为泛化估算，仅供参考，实际因公司/年份/个人情况差异较大。Carry实现周期长，并非保证收入。',
    disclaimerEn: 'Salary ranges above are generalized estimates for reference only; actual figures vary significantly by firm, year, and individual circumstances. Carry realization has a long cycle and is not guaranteed income.',
    typicalDay: [
      '9:00 — 周一组合评审会：回顾所有持仓企业上周的KPI指标（收入/EBITDA/现金流），标注需要干预的问题',
      '10:00-13:00 — 新项目评估：阅读目标公司IM（信息备忘录），完成快速财务分析，判断是否值得进入下一轮尽调',
      '13:00-16:00 — 更新LBO模型（基于最新财务数据），调整退出倍数敏感性区间，准备IC会议材料',
      '16:00-18:00 — 尽调协调：与律所/会计师对接进度，整理未解答的DD问题清单',
      '18:00+ — 撰写/修改IC Memo初稿，等待合伙人反馈后迭代修改',
    ],
    typicalDayEn: [
      '9:00 — Monday portfolio review: recap all portfolio companies\' last week KPIs (revenue/EBITDA/cash flow), flag issues requiring intervention',
      '10:00-13:00 — New deal evaluation: read target\'s IM (information memorandum), complete quick financial analysis, decide whether to proceed to full due diligence',
      '13:00-16:00 — Update LBO model (with latest financials), adjust exit multiple sensitivity range, prepare IC meeting materials',
      '16:00-18:00 — DD coordination: track progress with law firm/accounting firm, compile list of outstanding DD questions',
      '18:00+ — Draft/revise IC Memo, iterate after partner feedback',
    ],
  },
  {
    id: 'Quant',
    title: '量化金融 (Quant)',
    titleEn: 'Quantitative Finance',
    icon: '🤖',
    color: '#38bdf8',
    tagline: '用数学与算法系统性地寻找可持续的市场统计套利机会',
    taglineEn: 'Using math and algorithms to systematically find sustainable statistical edges in markets',
    description: 'Quant角色分三类：①量化研究员（QR）：开发Alpha因子，核心是"寻找市场尚未定价的规律"；②量化交易员（QT）：执行和优化策略，关注交易成本和市场冲击；③量化开发（QD）：搭建交易系统基础设施，追求纳秒级执行。薪资天花板在所有金融岗位中最高，但门槛（数理+编程双强）也最高。',
    descriptionEn: 'Quant roles split into three types: ① Quantitative Researcher (QR): develops alpha signals — core is "finding patterns the market hasn\'t priced yet"; ② Quantitative Trader (QT): executes and optimizes strategies, focused on transaction costs and market impact; ③ Quantitative Developer (QD): builds trading system infrastructure, targeting nanosecond execution. Highest compensation ceiling across all finance roles, but also highest barrier (requires both elite math AND programming).',
    coreScenario: '典型场景（量化研究员）：你发现一个基于财报质量的选股因子——低应计利润（Accruals，代理盈余操纵程度）的股票未来6个月平均跑赢高应计利润股票约3%（年化）。你需要：①用过去10年A股历史数据回测，计算因子的IC均值、Sharpe Ratio（目标＞1.0）、最大回撤；②检验是否有行业集中度偏差（该因子是否在特定行业过度暴露，导致"因子收益"其实是"行业Beta收益"）；③测算实际容量（加入多少规模的资金会通过市场冲击让因子失效）；④将该因子纳入多因子组合（与动量/低波动因子）测试是否提升组合Sharpe。',
    coreScenarioEn: 'Typical scenario (quantitative researcher): you discover a signal based on earnings quality — stocks with low accruals (proxy for earnings manipulation) outperform high-accruals stocks by ~3% over 6 months (annualized). You must: ① backtest on 10 years of A-share data, calculate factor IC mean, Sharpe Ratio (target >1.0), max drawdown; ② check for sector concentration bias (is the factor\'s "alpha" actually sector beta?); ③ estimate capacity (how much AUM causes the signal to decay via market impact?); ④ combine with momentum/low-volatility factors in a multi-factor portfolio and test whether portfolio Sharpe improves.',
    skills: [
      'Python精通（Pandas/NumPy数据处理、Scikit-learn建模、回测框架如Backtrader/Zipline；策略研究约70%时间在写Python）',
      'C++基础（高频交易或执行层面要求C++，用于压缩延迟到微秒/纳秒级别）',
      '统计学与概率论（时间序列分析、因子IC测试、多重检验校正如Bonferroni/BH，防止回测过拟合）',
      '机器学习（线性回归/随机森林/XGBoost用于因子组合；LSTM/Transformer用于时序预测；但要警惕过拟合）',
      '因子研究框架（Alpha因子的测试：IC/IR/换手率/容量分析；风险因子的中性化：行业/市值中性化处理）',
      '回测方法论（防止前视偏差/幸存者偏差/过拟合的具体操作：样本外测试、走样测试Walk-Forward Analysis）',
    ],
    skillsEn: [
      'Python proficiency (Pandas/NumPy data processing, Scikit-learn modeling, backtesting frameworks like Backtrader/Zipline; ~70% of research time is Python)',
      'C++ basics (required for HFT or execution layer — compresses latency to microsecond/nanosecond level)',
      'Statistics and probability (time series analysis, factor IC testing, multiple testing correction like Bonferroni/BH to prevent backtest overfitting)',
      'Machine learning (linear regression/random forest/XGBoost for factor combination; LSTM/Transformer for time series prediction; watch for overfitting)',
      'Factor research framework (alpha factor testing: IC/IR/turnover/capacity analysis; risk factor neutralization: sector/market cap neutralization)',
      'Backtesting methodology (preventing look-ahead bias/survivorship bias/overfitting: out-of-sample testing, walk-forward analysis)',
    ],
    differentiators: [
      'vs. 销售与交易（S&T）：S&T交易员依赖人工判断和市场直觉，实时管理仓位；Quant开发完全系统化的算法，策略上线后由代码自动执行。两者在"量化交易台"（Quant Trading Desk）界限模糊，但传统S&T更强调人工决策，Quant更强调数学严谨性和代码质量。',
      'vs. 风险管理（Risk）：都使用数学/统计模型，但目标相反。Quant的目标是"赚取超额收益"（寻找Alpha），风险管理的目标是"识别和控制损失"（度量和管理Beta/风险暴露）。Quant希望发现别人没有发现的机会，Risk希望在坏事发生之前预警并阻止。',
      'vs. 资产管理（AM）：AM的主动管理依赖基本面分析和人工判断（对少数公司的深度了解）；Quant依赖大样本统计规律（跨市场、跨公司的系统性模式）。顶级机构内两者界限日益模糊（量化基本面/Smart Beta），但Quant几乎不做公司管理层访谈，AM几乎不写代码。',
    ],
    differentiatorsEn: [
      'vs. Sales & Trading (S&T): S&T traders rely on human judgment and market intuition; Quant develops fully algorithmic strategies executed by code once live. The line blurs at quant trading desks, but traditional S&T emphasizes human decision-making; Quant emphasizes mathematical rigor and code quality.',
      'vs. Risk Management: Both use mathematical/statistical models, but with opposite objectives. Quant aims to "generate excess returns" (find alpha); Risk aims to "identify and control losses" (measure and manage beta/risk exposure). Quant wants to discover opportunities others missed; Risk wants to warn and prevent bad outcomes before they happen.',
      'vs. Asset Management (AM): AM\'s active management relies on fundamental analysis and human judgment (deep knowledge of a few companies). Quant relies on large-sample statistical patterns (systematic cross-market, cross-company patterns). The line is blurring at top institutions (quantamental/Smart Beta), but Quant rarely conducts management interviews; AM rarely writes code.',
    ],
    certs: [
      'FRM（量化风险管理模块直接适用）：FRM的市场风险、信用风险和量化方法论内容与Quant研究员的日常工作高度相关，尤其是在做风险因子中性化和压力测试时。',
      'CFA（可选，部分Quant PM要求）：如果你目标是Quant Portfolio Manager（量化基金经理），CFA Level 3的组合管理框架对向LP/机构客户解释量化策略有帮助。',
      '数学/CS/物理硕士或博士学历（顶级量化机构的隐性要求）：Citadel/TwoSigma/幻方/九坤等顶级量化机构实际上将名校理工科硕博学历视为比任何证书更重要的筛选门槛。',
    ],
    certsEn: [
      'FRM (quantitative risk modules are directly applicable): FRM\'s market risk, credit risk, and quantitative methods content maps closely to Quant researcher daily work, especially for risk factor neutralization and stress testing.',
      'CFA (optional, required for some Quant PMs): If you target Quant Portfolio Manager, CFA Level 3 portfolio management framework helps explain quantitative strategies to LPs/institutional clients.',
      'Math/CS/Physics Master\'s or PhD (implicit requirement at elite quant firms): Citadel/Two Sigma/Ubiquant/Jiukun and other top quant firms treat elite STEM graduate degrees as more important than any certification.',
    ],
    entry: '数学/统计/物理/CS顶尖本科或硕博；强编程能力（LeetCode中等题流畅，Quant岗位通常有编程+统计双测试）；名校背景（985顶尖/MIT/CMU/剑桥等）几乎是门槛；顶级量化私募（幻方/九坤）有线上笔试，淘汰率极高',
    entryEn: 'Top math/statistics/physics/CS undergraduate or graduate degree; strong programming (LeetCode medium fluency, Quant roles typically have both coding AND statistics tests); elite school background (top 985/MIT/CMU/Cambridge) is near-essential; top quant private funds (Ubiquant/Jiukun) have online assessments with very high elimination rates',
    career: '初级研究员/工程师 → 高级研究员 → 策略主管 → 合伙人/PM；薪资弹性极大，顶级量化私募的高级研究员收入可超过大多数投行MD',
    careerEn: 'Junior Researcher/Engineer → Senior Researcher → Strategy Lead → Partner/PM; extremely wide comp range — senior researchers at elite quant funds can earn more than most investment bank MDs',
    salary: '国内头部量化私募初级研究员：¥40–100万；高级研究员/策略主管：¥200万+；顶尖美资量化机构：$150–300K+基础工资，奖金数倍于此',
    salaryEn: 'Top China quant funds junior researcher: RMB 400K-1M; senior researcher/strategy lead: RMB 2M+; Top US quantitative institutions: $150-300K+ base, bonus multiples of base',
    disclaimer: '以上薪资区间为泛化估算，仅供参考，实际因公司/年份/个人情况差异较大。顶级量化机构薪资明显高于行业均值，且差距随资历扩大。',
    disclaimerEn: 'Salary ranges above are generalized estimates for reference only; actual figures vary significantly by firm, year, and individual circumstances. Elite quant institutions pay significantly above market average, with the gap widening at senior levels.',
    typicalDay: [
      '9:00 — 查看策略昨日实盘表现（实际P&L vs. 模拟P&L的偏差是否在正常范围）',
      '9:30-12:00 — 因子研究：测试新因子（应计利润/分析师预期修正/资本支出异常），跑历史回测，分析IC序列和衰减速度',
      '12:00-14:00 — 代码Review：与同事讨论回测框架的优化，修复潜在的前视偏差（Look-Ahead Bias）问题',
      '14:00-17:00 — 读学术论文（AQR/NBER/Journal of Finance）寻找新的因子灵感；或分析近期策略回撤的归因',
      '17:00-18:30 — 与交易团队对接：确认明日策略的调仓信号和实际执行计划（尽量减少市场冲击）',
    ],
    typicalDayEn: [
      '9:00 — Review yesterday\'s live strategy performance (is actual P&L vs simulated P&L within normal deviation range?)',
      '9:30-12:00 — Factor research: test new factors (accruals/analyst revision/capex anomaly), run historical backtest, analyze IC series and decay speed',
      '12:00-14:00 — Code review: discuss backtesting framework optimization with colleagues, fix potential look-ahead bias issues',
      '14:00-17:00 — Read academic papers (AQR/NBER/Journal of Finance) for new factor ideas; or analyze recent strategy drawdown attribution',
      '17:00-18:30 — Coordinate with trading team: confirm tomorrow\'s strategy rebalancing signals and actual execution plan (minimize market impact)',
    ],
  },
  {
    id: 'CorpFinance',
    title: '企业财务 (Corporate Finance)',
    titleEn: 'Corporate Finance / FP&A',
    icon: '🏢',
    color: '#a78bfa',
    tagline: '企业内部的"财务大脑"，支撑战略决策、预算管理和资本结构优化',
    taglineEn: 'The internal "financial brain" of a corporation — supporting strategic decisions, budget management, and capital structure',
    description: '企业财务并非单一岗位，而是四个方向的集合：①FP&A（财务规划与分析）：做预算、滚动预测和管理层汇报；②Treasury（资金管理）：管理公司现金流、融资和外汇风险；③Corp Dev（企业并购发展）：公司内部的M&A和战略投资部门；④Financial Accounting（财务会计）：财报合规和外部审计对接。与IBD相比工作强度更合理，但薪资上限相对低。',
    descriptionEn: 'Corporate finance is not one role but four directions: ① FP&A (Financial Planning & Analysis): budgeting, rolling forecasts, management reporting; ② Treasury: managing company cash flows, financing, and FX risk; ③ Corp Dev (Corporate Development): the company\'s internal M&A and strategic investment function; ④ Financial Accounting: financial reporting compliance and external audit interface. More reasonable hours than IBD but a lower comp ceiling.',
    coreScenario: '典型场景（FP&A）：每月的第3个工作日是月度收盘日。你作为全国消费品公司的FP&A分析师，需要在下班前完成：①汇总全国8个大区的P&L实际数据，检查数据准确性；②与预算做差异分析（Variance Analysis）：标注超/低于预算的差异项，找出"收入低于预期"的根本原因（是区域，还是品类，还是渠道？）；③向CFO出具一页执行摘要（核心：3-5条有业务洞察的结论，不是数字罗列）；④更新全年滚动预测（Rolling Forecast），预测Q4旺季现金流需求，给出是否需要提前动用信用额度的建议。',
    coreScenarioEn: 'Typical scenario (FP&A): the 3rd business day of each month is the monthly close. As FP&A analyst for a national consumer goods company, you must complete before end of day: ① consolidate P&L actuals from 8 regional units, verify data accuracy; ② variance analysis vs budget: identify over/under-budget items, find the root cause of "revenue below plan" (is it regional, category, or channel?); ③ prepare a one-page executive summary for the CFO (core: 3-5 business insights, not a data dump); ④ update the rolling forecast, project Q4 peak season cash flow needs, recommend whether to draw on credit facilities in advance.',
    skills: [
      '财务规划与预算（Annual Budgeting + Rolling Forecast：将全公司的战略目标拆解为可执行的部门P&L预算，并持续追踪实际vs预期差异）',
      '管理报告制作（Management Reporting：将财务数据转化为CFO/CEO能直接用于决策的可视化摘要，重点在于"业务洞察"而非数字堆砌）',
      '差异分析（Variance Analysis：识别与预算/上期/行业基准的差异，深追根本原因并给出业务解释）',
      '现金流管理（Cash Flow Forecasting：13周滚动现金流预测，确保公司在任何时点的流动性充足）',
      'ERP系统操作（SAP / Oracle Financials：国内外大企业的财务数据几乎全部跑在ERP上，操作熟练度直接影响工作效率）',
      '项目投资评估（NPV/IRR分析：当业务部门提出新项目或资本支出申请，FP&A负责评估财务可行性并给出是否投资的建议）',
    ],
    skillsEn: [
      'Financial planning & budgeting (Annual Budgeting + Rolling Forecast: translate company strategic goals into actionable department-level P&L budgets and track actual vs expected variance)',
      'Management reporting: convert financial data into CFO/CEO-ready visual summaries focused on "business insights," not data dumps',
      'Variance analysis: identify budget/prior period/industry benchmark deviations, drill down to root cause, provide business explanation',
      'Cash flow management (13-week rolling cash flow forecast: ensure adequate liquidity at all times)',
      'ERP system proficiency (SAP / Oracle Financials: large companies run nearly all financial data through ERP — proficiency directly impacts work efficiency)',
      'Capital project evaluation (NPV/IRR analysis: when business units submit project or capex requests, FP&A evaluates financial viability and recommends approve/reject)',
    ],
    differentiators: [
      'vs. IBD：IBD是外部顾问，帮企业执行融资/并购，项目结束关系结束；Corp Finance是企业内部员工，与业务部门长期合作，对行业和公司的了解更深。IBD工作节奏以"项目"为单位，Corp Finance以"月度/季度财务周期"为节奏。工作强度：IBD峰值可达100小时/周，Corp Finance通常50-60小时/周，预算季可能短暂冲到70-80小时。',
      'vs. 股票研究（ER）：ER是从外部分析上市公司价值，Corp Finance是从内部管理公司的财务表现。ER分析师的观点是公开发布的研报，Corp Finance的分析是供内部管理层使用的保密报告。两者都要做财务建模，但ER关注"公司是否被市场错误定价"，Corp Finance关注"公司实际运营效率是否达到预期"。',
      'Corp Dev vs. IBD：Corp Dev是公司内部的M&A部门，执行本公司主导的并购；IBD是外部顾问，可能同时服务多个买方或卖方。Corp Dev分析师通常比IBD分析师有更强的"我们要不要做这笔收购"的战略判断（因为决策结果由公司自己承担），IBD更多是分析和说服。',
    ],
    differentiatorsEn: [
      'vs. IBD: IBD is an external advisor — the relationship ends when the deal closes. Corp Finance is an internal employee, working long-term with business units and developing deeper company/industry knowledge. IBD pace is deal-driven; Corp Finance is monthly/quarterly cycle-driven. Hours: IBD peak can hit 100+/week; Corp Finance typically 50-60, briefly 70-80 during budget season.',
      'vs. Equity Research (ER): ER analyzes listed companies\' value from the outside; Corp Finance manages a company\'s financial performance from the inside. ER analysis is published research; Corp Finance analysis is confidential management reporting. Both do financial modeling, but ER asks "is the company mispriced?"; Corp Finance asks "is operational performance meeting plan?"',
      'Corp Dev vs. IBD: Corp Dev is the company\'s internal M&A function executing acquisitions on its own behalf. IBD is the external advisor who may serve multiple buyers or sellers simultaneously. Corp Dev analysts have stronger "should we actually do this deal?" strategic judgment (they live with the consequences); IBD is more about analysis and persuasion.',
    ],
    certs: [
      'CPA注册会计师（国内FP&A/财务会计岗位高度认可）：CPA考试覆盖的会计准则、税务、审计知识是财务合规和财报制作的基础。国内大型企业（尤其是国企/会计师事务所体系出来的候选人）通常将CPA视为核心竞争力标志。',
      'CMA注册管理会计师（FP&A岗位最直接对应的认证）：CMA覆盖的内容（财务规划、绩效管理、决策分析、风险管理）几乎就是FP&A岗位的工作描述。如果你确定走企业财务路线而非投行，CMA比CFA更直接实用。',
      'CFA（如果有志于Corp Dev或转回买方）：Corp Dev经常需要对并购目标做估值分析，CFA的估值和财报分析模块有直接帮助。若长期计划从Corp Dev转回IBD或买方，CFA也是有价值的背书。',
    ],
    certsEn: [
      'CPA (highly valued in China for FP&A/accounting roles): CPA exam covers accounting standards, tax, and audit knowledge — foundational for financial compliance and reporting. Large Chinese enterprises (especially SOEs) and candidates from accounting firm backgrounds often see CPA as a key competitive differentiator.',
      'CMA (most directly relevant certification for FP&A): CMA content (financial planning, performance management, decision analysis, risk management) is essentially the job description of an FP&A role. If you\'re committed to corporate finance over banking, CMA is more directly practical than CFA.',
      'CFA (for Corp Dev or buy-side ambitions): Corp Dev frequently needs to value M&A targets — CFA valuation and financial reporting modules directly apply. If you plan to transition from Corp Dev back to IBD or buy-side, CFA is also a valuable credential.',
    ],
    entry: '会计/金融/经济学本科；大型外资企业（500强）财务岗重视英语能力和ERP系统经验；国内大型企业重视CPA资格；实习经历（四大会计师事务所的审计实习是很强的背景）；通常不像IBD那样有严格的"目标院校"筛选',
    entryEn: 'Accounting/finance/economics undergraduate; large MNC finance roles value English proficiency and ERP experience; large domestic firms value CPA; internship experience (Big 4 audit internship is a strong background); typically less strict "target school" screening than IBD',
    career: '财务分析师 → 高级分析师 → 财务经理 → 财务总监（CFO路径）；横向：转IBD/PE（Corp Dev经验是跳板）或转战略咨询',
    careerEn: 'Financial Analyst → Senior Analyst → Finance Manager → CFO track; lateral: to IBD/PE (Corp Dev experience is a bridge) or strategy consulting',
    salary: '国内外资500强初级：¥15–30万；国内头部民企：¥12–25万；美国初级：$60–90K；工时合理，晋升路径清晰',
    salaryEn: 'China MNC 500 junior: RMB 150-300K; top China private firms: RMB 120-250K; US junior: $60-90K; reasonable hours with clear promotion path',
    disclaimer: '以上薪资区间为泛化估算，仅供参考，实际因公司/年份/个人情况差异较大。',
    disclaimerEn: 'Salary ranges above are generalized estimates for reference only; actual figures vary significantly by firm, year, and individual circumstances.',
    typicalDay: [
      '9:00 — 晨会：各业务部门Finance BP（业务伙伴）汇报上周的预算执行情况，标注偏差超过5%的科目',
      '10:00-12:00 — 月度收盘工作（月初3天）：汇总ERP数据，核对分录，整理P&L实际数据',
      '12:00-14:00 — 与市场/销售部门同事沟通：解释"为什么上个月的市场推广费用超预算了12%"',
      '14:00-17:00 — 更新全年滚动预测：将最新的销售数据填入预测模型，调整Q3-Q4假设，测算全年利润区间',
      '17:00-18:00 — 准备CFO月度汇报材料（PPT）：一页Executive Summary + 三页详细差异分析',
    ],
    typicalDayEn: [
      '9:00 — Morning sync: finance business partners from each unit report last week\'s budget execution, flag items with >5% variance',
      '10:00-12:00 — Monthly close work (first 3 days of month): consolidate ERP data, verify journal entries, compile P&L actuals',
      '12:00-14:00 — Discuss with marketing/sales colleagues: explain "why last month\'s marketing spend was 12% over budget"',
      '14:00-17:00 — Update rolling forecast: enter latest sales data into forecast model, adjust Q3-Q4 assumptions, calculate full-year profit range',
      '17:00-18:00 — Prepare CFO monthly reporting materials (PPT): one-page executive summary + three-page detailed variance analysis',
    ],
  },
  {
    id: 'Risk',
    title: '风险管理与合规 (Risk & Compliance)',
    titleEn: 'Risk Management & Compliance',
    icon: '🛡️',
    color: '#fb923c',
    tagline: '识别、量化并控制金融机构各类风险，确保合规经营',
    taglineEn: 'Identify, quantify, and control all types of risk across a financial institution, ensuring regulatory compliance',
    description: '风险管理覆盖四个维度：①市场风险：量化交易台面的价格波动风险（VaR/Greeks）；②信用风险：评估借款方或交易对手违约概率；③流动性风险：确保机构在压力情景下仍有足够资金；④操作风险：控制由人为错误/系统故障/欺诈导致的损失。合规岗位确保机构遵守巴塞尔III、MiFID II、证监会规定等监管要求。随着全球监管趋严，该领域需求持续增长。',
    descriptionEn: 'Risk management covers four dimensions: ① Market risk: quantify price volatility risk on trading books (VaR/Greeks); ② Credit risk: assess borrower or counterparty default probability; ③ Liquidity risk: ensure the institution has sufficient funding under stress; ④ Operational risk: control losses from human error/system failure/fraud. Compliance ensures adherence to Basel III, MiFID II, CSRC regulations, etc. Demand is growing as global regulation intensifies.',
    coreScenario: '典型场景（市场风险分析师）：每日9:00你需要生成全行日度VaR报告，覆盖股票/利率/外汇/大宗商品4个资产类别。具体工作：①计算当日99%置信水平、10天持有期的VaR总量；②对比实际P&L与VaR预测——若实际亏损超过VaR（即"回测超标"），需要记录并在年度内不超过4次（巴塞尔III要求）；③定期更新压力测试情景（如"A股熔断重演"、"美联储加息100bps"对各交易台的影响）；④若某交易台的日内头寸超过风险限额（Risk Limit），需立即联系前台并出具正式报告上报。',
    coreScenarioEn: 'Typical scenario (market risk analyst): each morning at 9:00 you generate the full-bank daily VaR report covering equities/rates/FX/commodities. Specifically: ① calculate daily total VaR at 99% confidence, 10-day holding period; ② compare actual P&L vs VaR forecast — if actual loss exceeds VaR ("backtest exception"), record it (Basel III allows no more than 4 per year); ③ periodically update stress test scenarios ("A-share circuit breaker replay," "Fed emergency 100bps rate hike" impact on each trading desk); ④ if any desk\'s intraday position exceeds the risk limit, immediately contact front office and issue a formal escalation report.',
    skills: [
      'VaR建模（三种方法：①历史模拟法：直接用历史P&L分布；②方差-协方差法：假设正态分布计算；③蒙特卡洛模拟：随机模拟大量市场情景）',
      '压力测试（Stress Testing）：设计极端但合理的市场情景（历史情景：2008年金融危机/2015年A股熔断；假设情景：美联储意外加息300bps），计算其对组合的影响',
      '信用风险模型（PD/LGD/EAD三要素：违约概率×违约损失率×违约敞口额=预期损失，用于银行贷款拨备计算）',
      '巴塞尔III监管资本框架（CET1/Tier 1/Tier 2资本充足率计算；RWA风险加权资产的计算逻辑；FRTB新监管标准的实施）',
      '监管报告（向证监会/银保监/美联储定期报告风险敞口数据，格式严格，错误可能引发监管问询）',
      '模型验证（Model Validation）：独立评估前台使用的定价模型是否存在方法论缺陷，防止模型失效导致系统性风险低估',
    ],
    skillsEn: [
      'VaR modeling (three methods: ① Historical simulation: use historical P&L distribution directly; ② Variance-covariance: assume normal distribution; ③ Monte Carlo simulation: randomly simulate large number of market scenarios)',
      'Stress testing: design extreme but plausible market scenarios (historical: 2008 financial crisis / 2015 A-share circuit breaker; hypothetical: Fed surprise 300bps hike), calculate portfolio impact',
      'Credit risk model (PD/LGD/EAD: Default Probability × Loss Given Default × Exposure at Default = Expected Loss, used for bank loan provisions)',
      'Basel III regulatory capital framework (CET1/Tier 1/Tier 2 capital adequacy ratios; RWA risk-weighted asset calculation logic; FRTB new regulatory standard implementation)',
      'Regulatory reporting (periodic risk exposure reporting to CSRC/CBIRC/Fed — strict format requirements; errors can trigger regulatory inquiry)',
      'Model validation: independently assess whether front-office pricing models have methodological flaws, preventing systematic risk underestimation from model failure',
    ],
    differentiators: [
      'vs. 量化（Quant）：两者都用数学/统计模型，但目标相反。Risk的模型目的是"识别和限制风险"（你不希望风险事件发生）；Quant的模型目的是"从市场中赚取Alpha"（你希望发现别人未察觉的机会）。Risk是防御方，Quant是进攻方。Risk有大量合规/监管工作（需向监管机构解释模型假设），Quant几乎没有。',
      'vs. 销售与交易（S&T）：S&T是"第一道防线"（自行管理仓位风险），Risk是"第二道防线"（独立监督和限制第一道防线的风险行为）。两者目标有时冲突：S&T希望更大的风险限额（赚更多P&L），Risk希望更保守的限额（保护机构整体稳定）。Risk分析师有权叫停超限的交易台头寸。',
      'vs. 企业财务（Corp Finance）：Corp Finance管理的是企业的财务风险（外汇敞口/利率风险/流动性），属于非金融公司内部；Risk管理的是金融机构自身的交易风险，面对的是更复杂的金融产品和监管框架。两者薪资结构和职业路径差异显著。',
    ],
    differentiatorsEn: [
      'vs. Quant: Both use mathematical/statistical models, but with opposite objectives. Risk models aim to "identify and limit risk" (you don\'t want risk events to occur); Quant models aim to "generate alpha from markets" (you want to find opportunities others haven\'t spotted). Risk is the defense; Quant is the offense. Risk involves substantial compliance/regulatory work (explaining model assumptions to regulators); Quant rarely does.',
      'vs. Sales & Trading (S&T): S&T is the "first line of defense" (self-managing position risk); Risk is the "second line of defense" (independently overseeing and limiting the first line\'s risk-taking). Their goals sometimes conflict: S&T wants higher risk limits (more P&L); Risk wants more conservative limits (protecting institutional stability). Risk analysts have authority to halt positions that breach limits.',
      'vs. Corporate Finance: Corp Finance manages a non-financial company\'s financial risks (FX exposure/interest rate risk/liquidity); Risk manages a financial institution\'s own trading risks, dealing with more complex financial products and regulatory frameworks. Very different comp structures and career paths.',
    ],
    certs: [
      'FRM注册金融风险管理师（该领域最权威的认证，强烈推荐）：FRM考试内容（巴塞尔协议、VaR、信用风险、操作风险、流动性风险）就是风险岗位日常工作的直接教科书。与CFA相比，FRM更侧重监管框架和风险计量方法，对风险岗位的直接适用性是所有证书中最高的。',
      'PRM注册风险管理师（FRM的替代选项）：内容与FRM相似，在欧洲更为认可。如果你计划在欧洲金融机构工作，PRM可能更有价值。',
      'CFA（进阶选项，特别是做信用分析或组合风险管理时）：如果你的风险工作偏向信用风险或投资组合风险（而非纯市场风险），CFA的固定收益和权益估值模块有补充价值。',
    ],
    certsEn: [
      'FRM (Financial Risk Manager — the most authoritative certification in this field, strongly recommended): FRM exam content (Basel regulations, VaR, credit risk, operational risk, liquidity risk) is essentially the direct textbook for risk management daily work. Compared to CFA, FRM is more focused on regulatory frameworks and risk measurement methods — highest direct applicability of any certification for this role.',
      'PRM (Professional Risk Manager — FRM alternative): Similar content to FRM, more recognized in Europe. If you plan to work at European financial institutions, PRM may have higher value.',
      'CFA (advanced option, especially for credit analysis or portfolio risk management): If your risk work leans toward credit risk or portfolio risk (rather than pure market risk), CFA\'s fixed income and equity valuation modules provide complementary value.',
    ],
    entry: '数学/统计/金融/工程本科；FRM考取对求职帮助极大（显示你了解风险的专业框架）；编程加分（Python/R用于数据处理和模型实现）；部分岗位接受理工科非金融背景（模型验证岗位尤其欢迎数学/物理专业）',
    entryEn: 'Math/statistics/finance/engineering undergraduate; FRM certification significantly helps (demonstrates knowledge of professional risk frameworks); programming a plus (Python/R for data processing and model implementation); some roles accept non-finance STEM backgrounds (model validation especially welcomes math/physics)',
    career: '风险分析师 → 高级分析师 → 风险经理 → 风险主管 → 首席风险官（CRO路径）；横向：监管机构（证监会/银保监）、合规、内部审计',
    careerEn: 'Risk Analyst → Senior Analyst → Risk Manager → Head of Risk → Chief Risk Officer (CRO path); lateral: regulatory bodies (CSRC/CBIRC), compliance, internal audit',
    salary: '国内银行/证券公司初级：¥18–32万；外资银行：¥25–45万；美国初级：$70–100K；监管专家随资历薪资有显著溢价',
    salaryEn: 'China bank/broker junior: RMB 180-320K; foreign bank: RMB 250-450K; US junior: $70-100K; regulatory expertise commands a significant premium at senior levels',
    disclaimer: '以上薪资区间为泛化估算，仅供参考，实际因公司/年份/个人情况差异较大。',
    disclaimerEn: 'Salary ranges above are generalized estimates for reference only; actual figures vary significantly by firm, year, and individual circumstances.',
    typicalDay: [
      '8:30 — 查看隔夜市场波动，标注可能影响当日VaR计算的极端行情',
      '9:00-10:30 — 生成日度VaR报告，对比各交易台实际P&L，标注回测超标事件并记录原因',
      '10:30-12:00 — 审查新交易的风险敞口：前台提交了一笔新的利率互换交易，评估其对台面Delta/DV01的影响，确认是否在限额内',
      '13:00-15:00 — 压力测试更新：将最新的宏观情景（美联储会议纪要暗示更快加息节奏）纳入情景分析，重新计算各情景下的损失估算',
      '15:00-17:30 — 撰写监管报告（季度）：按监管机构规定格式整理风险敞口数据，与法务合规团队核对',
    ],
    typicalDayEn: [
      '8:30 — Review overnight market moves, flag any extreme events that could impact today\'s VaR calculation',
      '9:00-10:30 — Generate daily VaR report, compare each desk\'s actual P&L against VaR, document any backtest exceptions and root cause',
      '10:30-12:00 — Review new trade risk exposure: front office submitted a new interest rate swap; assess its delta/DV01 impact on the desk\'s book, confirm whether it\'s within limits',
      '13:00-15:00 — Update stress tests: incorporate latest macro scenario (Fed minutes suggesting faster rate hikes) into scenario analysis, recalculate loss estimates',
      '15:00-17:30 — Write regulatory report (quarterly): compile risk exposure data in the regulator\'s prescribed format, cross-check with legal compliance team',
    ],
  },
]
