// GENERATED by frontend/tools/gen_mobile_strings.py (source: ios/tools/l10n_catalog.py). Do not edit.
export const LANG_ORDER = ['en', 'ja', 'ko', 'fr']
export const STR = {
 "跟随系统": [
  "System",
  "システムに従う",
  "시스템 설정",
  "Système"
 ],
 "浅色": [
  "Light",
  "ライト",
  "라이트",
  "Clair"
 ],
 "深色": [
  "Dark",
  "ダーク",
  "다크",
  "Sombre"
 ],
 "外观": [
  "Appearance",
  "外観",
  "화면 스타일",
  "Apparence"
 ],
 "语言": [
  "Language",
  "言語",
  "언어",
  "Langue"
 ],
 "行情": [
  "Market",
  "マーケット",
  "시장",
  "Marché"
 ],
 "学习中心": [
  "Learning",
  "学習",
  "학습",
  "Apprentissage"
 ],
 "AI老师": [
  "AI Teacher",
  "AI先生",
  "AI 선생님",
  "Prof IA"
 ],
 "模拟盘": [
  "Paper Trade",
  "ペーパートレード",
  "모의투자",
  "Simulation"
 ],
 "服务器错误": [
  "Server error",
  "サーバーエラー",
  "서버 오류",
  "Erreur du serveur"
 ],
 "出错了：%@": [
  "Something went wrong: %@",
  "エラーが発生しました：%@",
  "오류가 발생했습니다: %@",
  "Une erreur est survenue : %@"
 ],
 "加载中": [
  "Loading",
  "読み込み中",
  "불러오는 중",
  "Chargement"
 ],
 "取消": [
  "Cancel",
  "キャンセル",
  "취소",
  "Annuler"
 ],
 "确定": [
  "OK",
  "OK",
  "확인",
  "OK"
 ],
 "关闭": [
  "Close",
  "閉じる",
  "닫기",
  "Fermer"
 ],
 "完成": [
  "Done",
  "完了",
  "완료",
  "Terminé"
 ],
 "编辑": [
  "Edit",
  "編集",
  "편집",
  "Modifier"
 ],
 "清除": [
  "Clear",
  "消去",
  "지우기",
  "Effacer"
 ],
 "重置": [
  "Reset",
  "リセット",
  "초기화",
  "Réinitialiser"
 ],
 "暂无结果": [
  "No results",
  "結果がありません",
  "결과 없음",
  "Aucun résultat"
 ],
 "亿": [
  "B",
  "億",
  "억",
  "Md"
 ],
 "万": [
  "",
  "万",
  "만",
  ""
 ],
 "股": [
  " sh",
  "株",
  "주",
  " act."
 ],
 "手": [
  " lots",
  "ロット",
  "랏",
  " lots"
 ],
 "10日": [
  "10D",
  "10日",
  "10일",
  "10 j"
 ],
 "30日": [
  "30D",
  "30日",
  "30일",
  "30 j"
 ],
 "60日": [
  "60D",
  "60日",
  "60일",
  "60 j"
 ],
 "120日": [
  "120D",
  "120日",
  "120일",
  "120 j"
 ],
 "1年": [
  "1Y",
  "1年",
  "1년",
  "1 an"
 ],
 "指标": [
  "Indicators",
  "指標",
  "지표",
  "Indicateurs"
 ],
 "超买:70": [
  "Overbought: 70",
  "買われすぎ:70",
  "과매수:70",
  "Surachat : 70"
 ],
 "超卖:30": [
  "Oversold: 30",
  "売られすぎ:30",
  "과매도:30",
  "Survente : 30"
 ],
 "开": [
  "O",
  "始",
  "시",
  "O"
 ],
 "高": [
  "H",
  "高",
  "고",
  "H"
 ],
 "低": [
  "L",
  "安",
  "저",
  "B"
 ],
 "收": [
  "C",
  "終",
  "종",
  "C"
 ],
 "今开": [
  "Open",
  "始値",
  "시가",
  "Ouverture"
 ],
 "昨收": [
  "Prev close",
  "前日終値",
  "전일 종가",
  "Clôture préc."
 ],
 "最高": [
  "High",
  "高値",
  "고가",
  "Plus haut"
 ],
 "最低": [
  "Low",
  "安値",
  "저가",
  "Plus bas"
 ],
 "成交量": [
  "Volume",
  "出来高",
  "거래량",
  "Volume"
 ],
 "成交额": [
  "Turnover",
  "売買代金",
  "거래대금",
  "Montant"
 ],
 "区间最低": [
  "Range low",
  "期間安値",
  "구간 저점",
  "Bas de période"
 ],
 "区间最高": [
  "Range high",
  "期間高値",
  "구간 고점",
  "Haut de période"
 ],
 "A股": [
  "A-Shares",
  "A株",
  "A주",
  "Actions A"
 ],
 "美股": [
  "US Stocks",
  "米国株",
  "미국주식",
  "Actions US"
 ],
 "A股大盘": [
  "A-Share Market",
  "A株市場",
  "A주 시장",
  "Marché A"
 ],
 "暂无指数数据，开盘后自动更新": [
  "No index data yet. Updates automatically when the market opens.",
  "指数データがありません。取引開始後に自動更新されます。",
  "지수 데이터가 없습니다. 장이 열리면 자동으로 업데이트됩니다.",
  "Pas encore de données. Mise à jour automatique à l'ouverture."
 ],
 "上证指数": [
  "Shanghai",
  "上海総合",
  "상하이종합",
  "Shanghai"
 ],
 "深证成指": [
  "Shenzhen",
  "深セン成分",
  "선전성분",
  "Shenzhen"
 ],
 "创业板指": [
  "ChiNext",
  "創業板",
  "차이넥스트",
  "ChiNext"
 ],
 "%lld 上涨": [
  "%lld up",
  "%lld 上昇",
  "%lld 상승",
  "%lld en hausse"
 ],
 "%lld 平盘": [
  "%lld flat",
  "%lld 横ばい",
  "%lld 보합",
  "%lld stables"
 ],
 "%lld 下跌": [
  "%lld down",
  "%lld 下落",
  "%lld 하락",
  "%lld en baisse"
 ],
 "自选股": [
  "Watchlist",
  "ウォッチリスト",
  "관심종목",
  "Favoris"
 ],
 "还没有自选股": [
  "No watchlist yet",
  "ウォッチリストは空です",
  "관심종목이 없습니다",
  "Aucun favori"
 ],
 "搜索股票，点详情页右上角的星标即可添加": [
  "Search a stock and tap the star on its page to add it",
  "銘柄を検索し、詳細画面右上の星をタップして追加",
  "종목을 검색하고 상세 화면 오른쪽 위 별을 눌러 추가하세요",
  "Recherchez une action et touchez l'étoile pour l'ajouter"
 ],
 "移出自选": [
  "Remove from watchlist",
  "ウォッチリストから削除",
  "관심종목에서 삭제",
  "Retirer des favoris"
 ],
 "行业板块": [
  "Sectors",
  "セクター",
  "업종",
  "Secteurs"
 ],
 "领涨 %@": [
  "Leader: %@",
  "首位: %@",
  "선두: %@",
  "Meneur : %@"
 ],
 "热门股票": [
  "Trending",
  "人気銘柄",
  "인기 종목",
  "Populaires"
 ],
 "暂无热门股数据，稍后下拉刷新": [
  "No trending stocks yet. Pull down to refresh later.",
  "人気銘柄がまだありません。後で引いて更新してください。",
  "인기 종목 데이터가 없습니다. 잠시 후 당겨서 새로고침하세요.",
  "Pas de données. Tirez pour actualiser plus tard."
 ],
 "最近搜索": [
  "Recent searches",
  "最近の検索",
  "최근 검색",
  "Recherches récentes"
 ],
 "%lld 只": [
  "%lld",
  "%lld銘柄",
  "%lld종목",
  "%lld"
 ],
 "相关新闻": [
  "Related news",
  "関連ニュース",
  "관련 뉴스",
  "Actualités"
 ],
 "利好": [
  "Bullish",
  "好材料",
  "호재",
  "Haussier"
 ],
 "中性": [
  "Neutral",
  "中立",
  "중립",
  "Neutre"
 ],
 "利空": [
  "Bearish",
  "悪材料",
  "악재",
  "Baissier"
 ],
 "情感 %@": [
  "Sentiment %@",
  "センチメント %@",
  "감성 %@",
  "Sentiment %@"
 ],
 "持仓": [
  "Positions",
  "保有銘柄",
  "보유 종목",
  "Positions"
 ],
 "暂无持仓，点击 + 买入第一只股票": [
  "No positions yet. Tap + to buy your first stock.",
  "保有銘柄がありません。+ をタップして最初の銘柄を購入しましょう。",
  "보유 종목이 없습니다. + 를 눌러 첫 종목을 매수하세요.",
  "Aucune position. Touchez + pour acheter votre première action."
 ],
 "最近交易": [
  "Recent trades",
  "最近の取引",
  "최근 거래",
  "Transactions récentes"
 ],
 "A股账户": [
  "A-Share account",
  "A株口座",
  "A주 계좌",
  "Compte A"
 ],
 "美股账户": [
  "US account",
  "米国株口座",
  "미국주식 계좌",
  "Compte US"
 ],
 "总收益率": [
  "Total return",
  "総リターン",
  "총 수익률",
  "Rendement total"
 ],
 "可用现金": [
  "Cash available",
  "利用可能な現金",
  "사용 가능 현금",
  "Liquidités"
 ],
 "仅供学习": [
  "For learning only",
  "学習用のみ",
  "학습용",
  "À but éducatif"
 ],
 "不构成投资建议": [
  "Not investment advice",
  "投資助言ではありません",
  "투자 조언이 아닙니다",
  "Pas un conseil en investissement"
 ],
 "%lld股 · 均价%@": [
  "%lld sh · avg %@",
  "%lld株 · 平均 %@",
  "%lld주 · 평단 %@",
  "%lld act. · moy. %@"
 ],
 "%lld股 @ %@": [
  "%lld sh @ %@",
  "%lld株 @ %@",
  "%lld주 @ %@",
  "%lld act. @ %@"
 ],
 "买": [
  "B",
  "買",
  "매수",
  "A"
 ],
 "卖": [
  "S",
  "売",
  "매도",
  "V"
 ],
 "加载排行榜…": [
  "Loading leaderboard…",
  "ランキングを読み込み中…",
  "순위 불러오는 중…",
  "Chargement du classement…"
 ],
 "收益排行榜": [
  "Leaderboard",
  "ランキング",
  "수익 순위",
  "Classement"
 ],
 "（我）": [
  " (me)",
  "（自分）",
  "(나)",
  " (moi)"
 ],
 "我": [
  "Me",
  "自分",
  "나",
  "Moi"
 ],
 "确认重置账户": [
  "Reset account?",
  "口座をリセットしますか？",
  "계좌를 초기화할까요?",
  "Réinitialiser le compte ?"
 ],
 "所有持仓和交易记录将清除，初始资金将恢复至 100万元（A股）/ $10万（美股）。": [
  "All positions and trades will be cleared. Starting cash is restored to ¥1,000,000 (A-shares) / $100,000 (US).",
  "すべての保有銘柄と取引履歴が消去され、初期資金が 100万元（A株）/ 10万ドル（米国株）に戻ります。",
  "모든 보유 종목과 거래 기록이 삭제되고 초기 자금이 100만 위안(A주) / 10만 달러(미국)로 복원됩니다.",
  "Toutes les positions et transactions seront effacées. Capital initial : 1 000 000 ¥ (A) / 100 000 $ (US)."
 ],
 "交易失败": [
  "Trade failed",
  "取引に失敗しました",
  "거래 실패",
  "Échec de la transaction"
 ],
 "交易处理中…": [
  "Processing trade…",
  "取引を処理中…",
  "거래 처리 중…",
  "Traitement en cours…"
 ],
 "买入": [
  "Buy",
  "買い",
  "매수",
  "Acheter"
 ],
 "卖出": [
  "Sell",
  "売り",
  "매도",
  "Vendre"
 ],
 "A股 · 股票代码": [
  "A-Shares · Code",
  "A株 · 銘柄コード",
  "A주 · 종목 코드",
  "Actions A · Code"
 ],
 "美股 · 股票代码": [
  "US · Ticker",
  "米国株 · ティッカー",
  "미국 · 티커",
  "US · Symbole"
 ],
 "如 000001": [
  "e.g. 000001",
  "例: 000001",
  "예: 000001",
  "ex. 000001"
 ],
 "如 AAPL": [
  "e.g. AAPL",
  "例: AAPL",
  "예: AAPL",
  "ex. AAPL"
 ],
 "现价": [
  "Price",
  "現在値",
  "현재가",
  "Cours"
 ],
 "成本": [
  "Cost",
  "取得単価",
  "매입가",
  "Coût"
 ],
 "可卖/持有": [
  "Sellable/Held",
  "売却可/保有",
  "매도가능/보유",
  "Vendable/Détenu"
 ],
 "T+1：今日买入部分明日可卖": [
  "T+1: shares bought today can be sold tomorrow",
  "T+1: 本日購入分は翌日に売却可能",
  "T+1: 오늘 매수한 수량은 내일 매도 가능",
  "T+1 : les actions achetées aujourd'hui sont vendables demain"
 ],
 "T+2：部分持仓尚未结算": [
  "T+2: some shares have not settled yet",
  "T+2: 一部の保有分は未決済です",
  "T+2: 일부 보유 수량은 아직 결제되지 않았습니다",
  "T+2 : certaines actions ne sont pas encore réglées"
 ],
 "股数（100 的整数倍）": [
  "Shares (multiples of 100)",
  "株数（100株単位）",
  "수량 (100주 단위)",
  "Actions (multiples de 100)"
 ],
 "股数": [
  "Shares",
  "株数",
  "수량",
  "Actions"
 ],
 "最多 %lld": [
  "Max %lld",
  "最大 %lld",
  "최대 %lld",
  "Max %lld"
 ],
 "已按 100 股整数倍调整为 %lld 股": [
  "Adjusted to a multiple of 100: %lld shares",
  "100株単位に調整しました: %lld株",
  "100주 단위로 조정됨: %lld주",
  "Ajusté à un multiple de 100 : %lld actions"
 ],
 "1/4": [
  "1/4",
  "1/4",
  "1/4",
  "1/4"
 ],
 "1/2": [
  "1/2",
  "1/2",
  "1/2",
  "1/2"
 ],
 "3/4": [
  "3/4",
  "3/4",
  "3/4",
  "3/4"
 ],
 "全部": [
  "All",
  "全部",
  "전부",
  "Tout"
 ],
 "预计成交金额": [
  "Estimated proceeds",
  "約定金額（概算）",
  "예상 체결금액",
  "Montant estimé"
 ],
 "手续费约": [
  "Est. fees",
  "手数料（概算）",
  "예상 수수료",
  "Frais estimés"
 ],
 "预计盈亏": [
  "Est. P&L",
  "損益（概算）",
  "예상 손익",
  "P&L estimé"
 ],
 "确认买入 %lld 股": [
  "Confirm buy %lld shares",
  "%lld株を買う",
  "%lld주 매수 확정",
  "Confirmer l'achat de %lld actions"
 ],
 "确认卖出 %lld 股": [
  "Confirm sell %lld shares",
  "%lld株を売る",
  "%lld주 매도 확정",
  "Confirmer la vente de %lld actions"
 ],
 "仅供学习，不构成投资建议。实际成交价以服务器返回为准。": [
  "For learning only, not investment advice. The actual fill price is determined by the server.",
  "学習目的のみで、投資助言ではありません。実際の約定価格はサーバーの返す値に従います。",
  "학습용이며 투자 조언이 아닙니다. 실제 체결가는 서버 응답을 따릅니다.",
  "À but éducatif, pas un conseil en investissement. Le prix d'exécution réel est fixé par le serveur."
 ],
 "股票入门": [
  "Stock Basics",
  "株式入門",
  "주식 입문",
  "Bases de la bourse"
 ],
 "学习进度": [
  "Progress",
  "学習の進捗",
  "학습 진도",
  "Progression"
 ],
 "%lld/%lld 已学完": [
  "%lld/%lld completed",
  "%lld/%lld 完了",
  "%lld/%lld 완료",
  "%lld/%lld terminés"
 ],
 "%lld 个主题": [
  "%lld topics",
  "%lld トピック",
  "%lld개 주제",
  "%lld sujets"
 ],
 "%lld 个章节": [
  "%lld sections",
  "%lld セクション",
  "%lld개 섹션",
  "%lld sections"
 ],
 "已学完": [
  "Completed",
  "学習済み",
  "학습 완료",
  "Terminé"
 ],
 "标记为已学完": [
  "Mark as completed",
  "学習済みにする",
  "학습 완료로 표시",
  "Marquer comme terminé"
 ],
 "关键术语": [
  "Key terms",
  "重要用語",
  "핵심 용어",
  "Termes clés"
 ],
 "真实案例": [
  "Real-world example",
  "実例",
  "실제 사례",
  "Exemple concret"
 ],
 "考试技巧": [
  "Exam tip",
  "試験のコツ",
  "시험 팁",
  "Conseil d'examen"
 ],
 "AI股票老师": [
  "AI Stock Teacher",
  "AI株式の先生",
  "AI 주식 선생님",
  "Prof de bourse IA"
 ],
 "股票、基金、经济学，有问必答": [
  "Stocks, funds, economics — ask me anything",
  "株式・ファンド・経済学、何でも聞いてください",
  "주식, 펀드, 경제학 무엇이든 물어보세요",
  "Actions, fonds, économie : posez vos questions"
 ],
 "快速提问": [
  "Quick questions",
  "クイック質問",
  "빠른 질문",
  "Questions rapides"
 ],
 "什么是K线图": [
  "What is a candlestick chart?",
  "ローソク足チャートとは？",
  "캔들 차트란 무엇인가요?",
  "Qu'est-ce qu'un graphique en chandeliers ?"
 ],
 "PE比率怎么看": [
  "How do I read the P/E ratio?",
  "PERの見方は？",
  "PER은 어떻게 보나요?",
  "Comment lire le PER ?"
 ],
 "股票和基金区别": [
  "Stocks vs. funds",
  "株式とファンドの違い",
  "주식과 펀드의 차이",
  "Actions vs fonds"
 ],
 "如何看财报": [
  "How to read financial reports",
  "決算書の読み方",
  "재무제표 보는 법",
  "Lire un rapport financier"
 ],
 "什么是止损": [
  "What is a stop-loss?",
  "損切りとは？",
  "손절이란?",
  "Qu'est-ce qu'un stop-loss ?"
 ],
 "分散投资原则": [
  "Diversification principles",
  "分散投資の原則",
  "분산 투자 원칙",
  "Principes de diversification"
 ],
 "仅供学习，不构成投资建议": [
  "For learning only. Not investment advice.",
  "学習目的のみ。投資助言ではありません。",
  "학습용입니다. 투자 조언이 아닙니다.",
  "À but éducatif. Pas un conseil en investissement."
 ],
 "输入问题…": [
  "Ask a question…",
  "質問を入力…",
  "질문을 입력하세요…",
  "Posez une question…"
 ],
 "关于": [
  "About",
  "このアプリについて",
  "정보",
  "À propos"
 ],
 "开发者": [
  "Developer",
  "開発者",
  "개발자",
  "Développeur"
 ],
 "网站": [
  "Website",
  "ウェブサイト",
  "웹사이트",
  "Site web"
 ],
 "访问网站": [
  "Visit website",
  "ウェブサイトを開く",
  "웹사이트 방문",
  "Visiter le site"
 ],
 "法律": [
  "Legal",
  "法的情報",
  "법적 고지",
  "Mentions légales"
 ],
 "隐私政策 / Privacy Policy": [
  "Privacy Policy",
  "プライバシーポリシー",
  "개인정보 처리방침",
  "Politique de confidentialité"
 ],
 "免责声明": [
  "Disclaimer",
  "免責事項",
  "면책 조항",
  "Avertissement"
 ],
 "本应用仅供学习和教育目的，不构成任何投资建议。股市有风险，投资需谨慎。行情数据可能存在延迟。AI 老师内容由 AI 生成，仅供参考。": [
  "This app is for learning and education only and does not constitute investment advice. Investing involves risk. Market data may be delayed. AI Teacher content is AI-generated and for reference only.",
  "本アプリは学習・教育目的のみで、投資助言ではありません。投資にはリスクが伴います。相場データは遅延する場合があります。AI先生の内容はAIが生成したもので、参考情報です。",
  "이 앱은 학습 및 교육 목적이며 투자 조언이 아닙니다. 투자에는 위험이 따르며 시세 데이터는 지연될 수 있습니다. AI 선생님의 내용은 AI가 생성한 참고용 정보입니다.",
  "Cette application est à but éducatif et ne constitue pas un conseil en investissement. Investir comporte des risques. Les données peuvent être différées. Le contenu du Prof IA est généré par IA, à titre indicatif."
 ],
 "数据": [
  "Data",
  "データ",
  "데이터",
  "Données"
 ],
 "数据说明": [
  "About your data",
  "データについて",
  "데이터 안내",
  "À propos de vos données"
 ],
 "模拟盘数据和 AI 对话记录存储在服务器上，通过设备匿名 ID 关联，不绑定任何个人身份。重置账户将永久删除所有相关数据。": [
  "Paper-trading data and AI chats are stored on our server and linked to an anonymous device ID, not to any personal identity. Resetting the account permanently deletes the related data.",
  "ペーパートレードのデータとAIとの会話は、端末の匿名IDに紐づけてサーバーに保存され、個人を特定する情報とは結びつきません。口座をリセットすると関連データは完全に削除されます。",
  "모의투자 데이터와 AI 대화 기록은 기기 익명 ID로 서버에 저장되며 개인 신원과 연결되지 않습니다. 계좌를 초기화하면 관련 데이터가 영구 삭제됩니다.",
  "Les données de simulation et les conversations IA sont stockées sur le serveur, liées à un identifiant d'appareil anonyme, sans identité personnelle. Réinitialiser le compte supprime définitivement ces données."
 ],
 "联系 / 删除数据请求": [
  "Contact / data deletion request",
  "お問い合わせ / データ削除の依頼",
  "문의 / 데이터 삭제 요청",
  "Contact / demande de suppression"
 ],
 "Best Friend Stock · 版本 1.0": [
  "Best Friend Stock · Version 1.0",
  "Best Friend Stock · バージョン 1.0",
  "Best Friend Stock · 버전 1.0",
  "Best Friend Stock · Version 1.0"
 ],
 "全球市场": [
  "Global Markets",
  "グローバル市場",
  "글로벌 시장",
  "Marchés mondiaux"
 ],
 "美股情绪": [
  "US Sentiment",
  "米国株センチメント",
  "미국 주식 심리",
  "Sentiment US"
 ],
 "A股情绪": [
  "A-Share Sentiment",
  "A株センチメント",
  "A주 심리",
  "Sentiment A"
 ],
 "极度恐慌": [
  "Extreme Fear",
  "極度の恐怖",
  "극단적 공포",
  "Peur extrême"
 ],
 "恐慌": [
  "Fear",
  "恐怖",
  "공포",
  "Peur"
 ],
 "贪婪": [
  "Greed",
  "強欲",
  "탐욕",
  "Avidité"
 ],
 "极度贪婪": [
  "Extreme Greed",
  "極度の強欲",
  "극단적 탐욕",
  "Avidité extrême"
 ],
 "清空对话": [
  "Clear chat",
  "会話を消去",
  "대화 지우기",
  "Effacer la conversation"
 ],
 "停止生成": [
  "Stop generating",
  "生成を停止",
  "생성 중지",
  "Arrêter la génération"
 ],
 "发送": [
  "Send",
  "送信",
  "보내기",
  "Envoyer"
 ],
 "重置账户": [
  "Reset account",
  "口座をリセット",
  "계좌 초기화",
  "Réinitialiser le compte"
 ],
 "加入自选": [
  "Add to watchlist",
  "ウォッチリストに追加",
  "관심종목에 추가",
  "Ajouter aux favoris"
 ],
 "减少": [
  "Decrease",
  "減らす",
  "줄이기",
  "Diminuer"
 ],
 "增加": [
  "Increase",
  "増やす",
  "늘리기",
  "Augmenter"
 ],
 "白酒": [
  "Baijiu",
  "白酒",
  "백주",
  "Baijiu"
 ],
 "银行": [
  "Banks",
  "銀行",
  "은행",
  "Banques"
 ],
 "新能源": [
  "New Energy",
  "新エネルギー",
  "신에너지",
  "Renouvelables"
 ],
 "科技": [
  "Tech",
  "テクノロジー",
  "기술",
  "Technologie"
 ],
 "医药": [
  "Pharma",
  "医薬",
  "제약",
  "Pharma"
 ],
 "消费": [
  "Consumer",
  "消費",
  "소비",
  "Consommation"
 ],
 "军工": [
  "Defense",
  "防衛",
  "방산",
  "Défense"
 ],
 "地产": [
  "Real Estate",
  "不動産",
  "부동산",
  "Immobilier"
 ],
 "能源": [
  "Energy",
  "エネルギー",
  "에너지",
  "Énergie"
 ],
 "电力": [
  "Utilities",
  "電力",
  "전력",
  "Électricité"
 ],
 "化工": [
  "Chemicals",
  "化学",
  "화학",
  "Chimie"
 ],
 "汽车": [
  "Autos",
  "自動車",
  "자동차",
  "Automobile"
 ],
 "传媒": [
  "Media",
  "メディア",
  "미디어",
  "Médias"
 ],
 "加载中...": [
  "Loading...",
  "読み込み中...",
  "불러오는 중...",
  "Chargement..."
 ],
 "重试": [
  "Retry",
  "再試行",
  "다시 시도",
  "Réessayer"
 ],
 "请求超时，请重试": [
  "Request timed out. Please retry.",
  "リクエストがタイムアウトしました。もう一度お試しください。",
  "요청 시간이 초과되었습니다. 다시 시도하세요.",
  "Délai dépassé. Veuillez réessayer."
 ],
 "网络错误": [
  "Network error",
  "ネットワークエラー",
  "네트워크 오류",
  "Erreur réseau"
 ],
 "数据解析失败": [
  "Data parsing failed",
  "データの解析に失敗しました",
  "데이터 해석 실패",
  "Échec de l'analyse des données"
 ],
 "搜索股票": [
  "Search stocks",
  "銘柄を検索",
  "종목 검색",
  "Rechercher une action"
 ],
 "切换到电脑版": [
  "Desktop site",
  "デスクトップ版",
  "PC 버전",
  "Version bureau"
 ],
 "切换到手机版": [
  "Mobile site",
  "モバイル版",
  "모바일 버전",
  "Version mobile"
 ],
 "搜索股票或代码": [
  "Search stocks or tickers",
  "銘柄名・コードで検索",
  "종목명 또는 코드 검색",
  "Rechercher une action ou un symbole"
 ],
 "暂无数据": [
  "No data",
  "データなし",
  "데이터 없음",
  "Aucune donnée"
 ],
 "加载失败": [
  "Failed to load",
  "読み込みに失敗しました",
  "불러오기 실패",
  "Échec du chargement"
 ],
 "未找到相关股票": [
  "No stocks found",
  "該当する銘柄がありません",
  "검색 결과가 없습니다",
  "Aucune action trouvée"
 ],
 "返回": [
  "Back",
  "戻る",
  "뒤로",
  "Retour"
 ],
 "日K": [
  "Daily",
  "日足",
  "일봉",
  "Jour"
 ],
 "周K": [
  "Weekly",
  "週足",
  "주봉",
  "Semaine"
 ],
 "月K": [
  "Monthly",
  "月足",
  "월봉",
  "Mois"
 ],
 "近期搜索": [
  "Recent",
  "最近",
  "최근",
  "Récents"
 ],
 "登录后可同步自选股": [
  "Sign in on the desktop site to sync your watchlist",
  "デスクトップ版でログインするとウォッチリストを同期できます",
  "PC 버전에서 로그인하면 관심종목이 동기화됩니다",
  "Connectez-vous sur la version bureau pour synchroniser"
 ],
 "网络似乎不稳定，已显示上次的数据": [
  "Network looks unstable, showing your last data",
  "ネットワークが不安定です。前回のデータを表示しています",
  "네트워크가 불안정합니다. 이전 데이터를 표시합니다",
  "Réseau instable, dernières données affichées"
 ],
 "在 App 内置浏览器中打开": [
  "Opened in an in-app browser",
  "アプリ内ブラウザで開いています",
  "앱 내 브라우저에서 열림",
  "Ouvert dans un navigateur intégré"
 ],
 "用系统浏览器打开": [
  "Open in browser",
  "ブラウザで開く",
  "브라우저에서 열기",
  "Ouvrir dans le navigateur"
 ],
 "更新于 %@": [
  "Updated %@",
  "更新: %@",
  "업데이트: %@",
  "Mis à jour : %@"
 ],
 "买入成功": [
  "Order filled",
  "約定しました",
  "체결되었습니다",
  "Ordre exécuté"
 ],
 "股票代码": [
  "Symbol",
  "銘柄コード",
  "종목 코드",
  "Symbole"
 ],
 "数量": [
  "Shares",
  "数量",
  "수량",
  "Quantité"
 ],
 "最新价": [
  "Price",
  "現在値",
  "현재가",
  "Cours"
 ],
 "涨跌幅": [
  "Change",
  "騰落率",
  "등락률",
  "Variation"
 ],
 "没有持仓": [
  "No positions",
  "保有銘柄なし",
  "보유 종목 없음",
  "Aucune position"
 ]
}
