// GENERATED by frontend/tools/gen_mobile_strings.py (source: ios/tools/l10n_catalog.py). Do not edit.
export const LANG_ORDER = ['en', 'ja', 'ko', 'fr']
export const STR = {
 "跟随系统": [
  "System",
  "システムに従う",
  "시스템 설정",
  "Système"
 ],
 "浅色": [
  "Light",
  "ライト",
  "라이트",
  "Clair"
 ],
 "深色": [
  "Dark",
  "ダーク",
  "다크",
  "Sombre"
 ],
 "外观": [
  "Appearance",
  "外観",
  "화면 스타일",
  "Apparence"
 ],
 "语言": [
  "Language",
  "言語",
  "언어",
  "Langue"
 ],
 "行情": [
  "Market",
  "マーケット",
  "시장",
  "Marché"
 ],
 "学习中心": [
  "Learning",
  "学習",
  "학습",
  "Apprentissage"
 ],
 "AI老师": [
  "AI Teacher",
  "AI先生",
  "AI 선생님",
  "Prof IA"
 ],
 "模拟盘": [
  "Paper Trade",
  "ペーパートレード",
  "모의투자",
  "Simulation"
 ],
 "服务器错误": [
  "Server error",
  "サーバーエラー",
  "서버 오류",
  "Erreur du serveur"
 ],
 "出错了：%@": [
  "Something went wrong: %@",
  "エラーが発生しました：%@",
  "오류가 발생했습니다: %@",
  "Une erreur est survenue : %@"
 ],
 "加载中": [
  "Loading",
  "読み込み中",
  "불러오는 중",
  "Chargement"
 ],
 "取消": [
  "Cancel",
  "キャンセル",
  "취소",
  "Annuler"
 ],
 "确定": [
  "OK",
  "OK",
  "확인",
  "OK"
 ],
 "关闭": [
  "Close",
  "閉じる",
  "닫기",
  "Fermer"
 ],
 "完成": [
  "Done",
  "完了",
  "완료",
  "Terminé"
 ],
 "编辑": [
  "Edit",
  "編集",
  "편집",
  "Modifier"
 ],
 "清除": [
  "Clear",
  "消去",
  "지우기",
  "Effacer"
 ],
 "重置": [
  "Reset",
  "リセット",
  "초기화",
  "Réinitialiser"
 ],
 "暂无结果": [
  "No results",
  "結果がありません",
  "결과 없음",
  "Aucun résultat"
 ],
 "亿": [
  "B",
  "億",
  "억",
  "Md"
 ],
 "万": [
  "",
  "万",
  "만",
  ""
 ],
 "股": [
  " sh",
  "株",
  "주",
  " act."
 ],
 "手": [
  " lots",
  "ロット",
  "랏",
  " lots"
 ],
 "10日": [
  "10D",
  "10日",
  "10일",
  "10 j"
 ],
 "30日": [
  "30D",
  "30日",
  "30일",
  "30 j"
 ],
 "60日": [
  "60D",
  "60日",
  "60일",
  "60 j"
 ],
 "120日": [
  "120D",
  "120日",
  "120일",
  "120 j"
 ],
 "1年": [
  "1Y",
  "1年",
  "1년",
  "1 an"
 ],
 "指标": [
  "Indicators",
  "指標",
  "지표",
  "Indicateurs"
 ],
 "超买:70": [
  "Overbought: 70",
  "買われすぎ:70",
  "과매수:70",
  "Surachat : 70"
 ],
 "超卖:30": [
  "Oversold: 30",
  "売られすぎ:30",
  "과매도:30",
  "Survente : 30"
 ],
 "开": [
  "O",
  "始",
  "시",
  "O"
 ],
 "高": [
  "H",
  "高",
  "고",
  "H"
 ],
 "低": [
  "L",
  "安",
  "저",
  "B"
 ],
 "收": [
  "C",
  "終",
  "종",
  "C"
 ],
 "今开": [
  "Open",
  "始値",
  "시가",
  "Ouverture"
 ],
 "昨收": [
  "Prev close",
  "前日終値",
  "전일 종가",
  "Clôture préc."
 ],
 "最高": [
  "High",
  "高値",
  "고가",
  "Plus haut"
 ],
 "最低": [
  "Low",
  "安値",
  "저가",
  "Plus bas"
 ],
 "成交量": [
  "Volume",
  "出来高",
  "거래량",
  "Volume"
 ],
 "成交额": [
  "Turnover",
  "売買代金",
  "거래대금",
  "Montant"
 ],
 "区间最低": [
  "Range low",
  "期間安値",
  "구간 저점",
  "Bas de période"
 ],
 "区间最高": [
  "Range high",
  "期間高値",
  "구간 고점",
  "Haut de période"
 ],
 "A股": [
  "A-Shares",
  "A株",
  "A주",
  "Actions A"
 ],
 "美股": [
  "US Stocks",
  "米国株",
  "미국주식",
  "Actions US"
 ],
 "A股大盘": [
  "A-Share Market",
  "A株市場",
  "A주 시장",
  "Marché A"
 ],
 "暂无指数数据，开盘后自动更新": [
  "No index data yet. Updates automatically when the market opens.",
  "指数データがありません。取引開始後に自動更新されます。",
  "지수 데이터가 없습니다. 장이 열리면 자동으로 업데이트됩니다.",
  "Pas encore de données. Mise à jour automatique à l'ouverture."
 ],
 "上证指数": [
  "Shanghai",
  "上海総合",
  "상하이종합",
  "Shanghai"
 ],
 "深证成指": [
  "Shenzhen",
  "深セン成分",
  "선전성분",
  "Shenzhen"
 ],
 "创业板指": [
  "ChiNext",
  "創業板",
  "차이넥스트",
  "ChiNext"
 ],
 "%lld 上涨": [
  "%lld up",
  "%lld 上昇",
  "%lld 상승",
  "%lld en hausse"
 ],
 "%lld 平盘": [
  "%lld flat",
  "%lld 横ばい",
  "%lld 보합",
  "%lld stables"
 ],
 "%lld 下跌": [
  "%lld down",
  "%lld 下落",
  "%lld 하락",
  "%lld en baisse"
 ],
 "自选股": [
  "Watchlist",
  "ウォッチリスト",
  "관심종목",
  "Favoris"
 ],
 "还没有自选股": [
  "No watchlist yet",
  "ウォッチリストは空です",
  "관심종목이 없습니다",
  "Aucun favori"
 ],
 "搜索股票，点详情页右上角的星标即可添加": [
  "Search a stock and tap the star on its page to add it",
  "銘柄を検索し、詳細画面右上の星をタップして追加",
  "종목을 검색하고 상세 화면 오른쪽 위 별을 눌러 추가하세요",
  "Recherchez une action et touchez l'étoile pour l'ajouter"
 ],
 "移出自选": [
  "Remove from watchlist",
  "ウォッチリストから削除",
  "관심종목에서 삭제",
  "Retirer des favoris"
 ],
 "行业板块": [
  "Sectors",
  "セクター",
  "업종",
  "Secteurs"
 ],
 "领涨 %@": [
  "Leader: %@",
  "首位: %@",
  "선두: %@",
  "Meneur : %@"
 ],
 "热门股票": [
  "Trending",
  "人気銘柄",
  "인기 종목",
  "Populaires"
 ],
 "暂无热门股数据，稍后下拉刷新": [
  "No trending stocks yet. Pull down to refresh later.",
  "人気銘柄がまだありません。後で引いて更新してください。",
  "인기 종목 데이터가 없습니다. 잠시 후 당겨서 새로고침하세요.",
  "Pas de données. Tirez pour actualiser plus tard."
 ],
 "最近搜索": [
  "Recent searches",
  "最近の検索",
  "최근 검색",
  "Recherches récentes"
 ],
 "%lld 只": [
  "%lld",
  "%lld銘柄",
  "%lld종목",
  "%lld"
 ],
 "相关新闻": [
  "Related news",
  "関連ニュース",
  "관련 뉴스",
  "Actualités"
 ],
 "利好": [
  "Bullish",
  "好材料",
  "호재",
  "Haussier"
 ],
 "中性": [
  "Neutral",
  "中立",
  "중립",
  "Neutre"
 ],
 "利空": [
  "Bearish",
  "悪材料",
  "악재",
  "Baissier"
 ],
 "情感 %@": [
  "Sentiment %@",
  "センチメント %@",
  "감성 %@",
  "Sentiment %@"
 ],
 "持仓": [
  "Positions",
  "保有銘柄",
  "보유 종목",
  "Positions"
 ],
 "暂无持仓，点击 + 买入第一只股票": [
  "No positions yet. Tap + to buy your first stock.",
  "保有銘柄がありません。+ をタップして最初の銘柄を購入しましょう。",
  "보유 종목이 없습니다. + 를 눌러 첫 종목을 매수하세요.",
  "Aucune position. Touchez + pour acheter votre première action."
 ],
 "最近交易": [
  "Recent trades",
  "最近の取引",
  "최근 거래",
  "Transactions récentes"
 ],
 "A股账户": [
  "A-Share account",
  "A株口座",
  "A주 계좌",
  "Compte A"
 ],
 "美股账户": [
  "US account",
  "米国株口座",
  "미국주식 계좌",
  "Compte US"
 ],
 "总收益率": [
  "Total return",
  "総リターン",
  "총 수익률",
  "Rendement total"
 ],
 "可用现金": [
  "Cash available",
  "利用可能な現金",
  "사용 가능 현금",
  "Liquidités"
 ],
 "仅供学习": [
  "For learning only",
  "学習用のみ",
  "학습용",
  "À but éducatif"
 ],
 "不构成投资建议": [
  "Not investment advice",
  "投資助言ではありません",
  "투자 조언이 아닙니다",
  "Pas un conseil en investissement"
 ],
 "%lld股 · 均价%@": [
  "%lld sh · avg %@",
  "%lld株 · 平均 %@",
  "%lld주 · 평단 %@",
  "%lld act. · moy. %@"
 ],
 "%lld股 @ %@": [
  "%lld sh @ %@",
  "%lld株 @ %@",
  "%lld주 @ %@",
  "%lld act. @ %@"
 ],
 "买": [
  "B",
  "買",
  "매수",
  "A"
 ],
 "卖": [
  "S",
  "売",
  "매도",
  "V"
 ],
 "加载排行榜…": [
  "Loading leaderboard…",
  "ランキングを読み込み中…",
  "순위 불러오는 중…",
  "Chargement du classement…"
 ],
 "收益排行榜": [
  "Leaderboard",
  "ランキング",
  "수익 순위",
  "Classement"
 ],
 "（我）": [
  " (me)",
  "（自分）",
  "(나)",
  " (moi)"
 ],
 "我": [
  "Me",
  "自分",
  "나",
  "Moi"
 ],
 "确认重置账户": [
  "Reset account?",
  "口座をリセットしますか？",
  "계좌를 초기화할까요?",
  "Réinitialiser le compte ?"
 ],
 "所有持仓和交易记录将清除，初始资金将恢复至 100万元（A股）/ $10万（美股）。": [
  "All positions and trades will be cleared. Starting cash is restored to ¥1,000,000 (A-shares) / $100,000 (US).",
  "すべての保有銘柄と取引履歴が消去され、初期資金が 100万元（A株）/ 10万ドル（米国株）に戻ります。",
  "모든 보유 종목과 거래 기록이 삭제되고 초기 자금이 100만 위안(A주) / 10만 달러(미국)로 복원됩니다.",
  "Toutes les positions et transactions seront effacées. Capital initial : 1 000 000 ¥ (A) / 100 000 $ (US)."
 ],
 "交易失败": [
  "Trade failed",
  "取引に失敗しました",
  "거래 실패",
  "Échec de la transaction"
 ],
 "交易处理中…": [
  "Processing trade…",
  "取引を処理中…",
  "거래 처리 중…",
  "Traitement en cours…"
 ],
 "买入": [
  "Buy",
  "買い",
  "매수",
  "Acheter"
 ],
 "卖出": [
  "Sell",
  "売り",
  "매도",
  "Vendre"
 ],
 "A股 · 股票代码": [
  "A-Shares · Code",
  "A株 · 銘柄コード",
  "A주 · 종목 코드",
  "Actions A · Code"
 ],
 "美股 · 股票代码": [
  "US · Ticker",
  "米国株 · ティッカー",
  "미국 · 티커",
  "US · Symbole"
 ],
 "如 000001": [
  "e.g. 000001",
  "例: 000001",
  "예: 000001",
  "ex. 000001"
 ],
 "如 AAPL": [
  "e.g. AAPL",
  "例: AAPL",
  "예: AAPL",
  "ex. AAPL"
 ],
 "现价": [
  "Price",
  "現在値",
  "현재가",
  "Cours"
 ],
 "成本": [
  "Cost",
  "取得単価",
  "매입가",
  "Coût"
 ],
 "可卖/持有": [
  "Sellable/Held",
  "売却可/保有",
  "매도가능/보유",
  "Vendable/Détenu"
 ],
 "T+1：今日买入部分明日可卖": [
  "T+1: shares bought today can be sold tomorrow",
  "T+1: 本日購入分は翌日に売却可能",
  "T+1: 오늘 매수한 수량은 내일 매도 가능",
  "T+1 : les actions achetées aujourd'hui sont vendables demain"
 ],
 "T+2：部分持仓尚未结算": [
  "T+2: some shares have not settled yet",
  "T+2: 一部の保有分は未決済です",
  "T+2: 일부 보유 수량은 아직 결제되지 않았습니다",
  "T+2 : certaines actions ne sont pas encore réglées"
 ],
 "股数（100 的整数倍）": [
  "Shares (multiples of 100)",
  "株数（100株単位）",
  "수량 (100주 단위)",
  "Actions (multiples de 100)"
 ],
 "股数": [
  "Shares",
  "株数",
  "수량",
  "Actions"
 ],
 "最多 %lld": [
  "Max %lld",
  "最大 %lld",
  "최대 %lld",
  "Max %lld"
 ],
 "已按 100 股整数倍调整为 %lld 股": [
  "Adjusted to a multiple of 100: %lld shares",
  "100株単位に調整しました: %lld株",
  "100주 단위로 조정됨: %lld주",
  "Ajusté à un multiple de 100 : %lld actions"
 ],
 "1/4": [
  "1/4",
  "1/4",
  "1/4",
  "1/4"
 ],
 "1/2": [
  "1/2",
  "1/2",
  "1/2",
  "1/2"
 ],
 "3/4": [
  "3/4",
  "3/4",
  "3/4",
  "3/4"
 ],
 "全部": [
  "All",
  "すべて",
  "전체",
  "Tous"
 ],
 "预计成交金额": [
  "Estimated proceeds",
  "約定金額（概算）",
  "예상 체결금액",
  "Montant estimé"
 ],
 "手续费约": [
  "Est. fees",
  "手数料（概算）",
  "예상 수수료",
  "Frais estimés"
 ],
 "预计盈亏": [
  "Est. P&L",
  "損益（概算）",
  "예상 손익",
  "P&L estimé"
 ],
 "确认买入 %lld 股": [
  "Confirm buy %lld shares",
  "%lld株を買う",
  "%lld주 매수 확정",
  "Confirmer l'achat de %lld actions"
 ],
 "确认卖出 %lld 股": [
  "Confirm sell %lld shares",
  "%lld株を売る",
  "%lld주 매도 확정",
  "Confirmer la vente de %lld actions"
 ],
 "仅供学习，不构成投资建议。实际成交价以服务器返回为准。": [
  "For learning only, not investment advice. The actual fill price is determined by the server.",
  "学習目的のみで、投資助言ではありません。実際の約定価格はサーバーの返す値に従います。",
  "학습용이며 투자 조언이 아닙니다. 실제 체결가는 서버 응답을 따릅니다.",
  "À but éducatif, pas un conseil en investissement. Le prix d'exécution réel est fixé par le serveur."
 ],
 "股票入门": [
  "Stock Basics",
  "株式入門",
  "주식 입문",
  "Bases de la bourse"
 ],
 "学习进度": [
  "Progress",
  "学習の進捗",
  "학습 진도",
  "Progression"
 ],
 "%lld/%lld 已学完": [
  "%lld/%lld completed",
  "%lld/%lld 完了",
  "%lld/%lld 완료",
  "%lld/%lld terminés"
 ],
 "%lld 个主题": [
  "%lld topics",
  "%lld トピック",
  "%lld개 주제",
  "%lld sujets"
 ],
 "%lld 个章节": [
  "%lld sections",
  "%lld セクション",
  "%lld개 섹션",
  "%lld sections"
 ],
 "已学完": [
  "Completed",
  "学習済み",
  "학습 완료",
  "Terminé"
 ],
 "标记为已学完": [
  "Mark as completed",
  "学習済みにする",
  "학습 완료로 표시",
  "Marquer comme terminé"
 ],
 "关键术语": [
  "Key terms",
  "重要用語",
  "핵심 용어",
  "Termes clés"
 ],
 "真实案例": [
  "Real-world example",
  "実例",
  "실제 사례",
  "Exemple concret"
 ],
 "考试技巧": [
  "Exam tip",
  "試験のコツ",
  "시험 팁",
  "Conseil d'examen"
 ],
 "AI股票老师": [
  "AI Stock Teacher",
  "AI株式の先生",
  "AI 주식 선생님",
  "Prof de bourse IA"
 ],
 "股票、基金、经济学，有问必答": [
  "Stocks, funds, economics — ask me anything",
  "株式・ファンド・経済学、何でも聞いてください",
  "주식, 펀드, 경제학 무엇이든 물어보세요",
  "Actions, fonds, économie : posez vos questions"
 ],
 "快速提问": [
  "Quick questions",
  "クイック質問",
  "빠른 질문",
  "Questions rapides"
 ],
 "什么是K线图": [
  "What is a candlestick chart?",
  "ローソク足チャートとは？",
  "캔들 차트란 무엇인가요?",
  "Qu'est-ce qu'un graphique en chandeliers ?"
 ],
 "PE比率怎么看": [
  "How do I read the P/E ratio?",
  "PERの見方は？",
  "PER은 어떻게 보나요?",
  "Comment lire le PER ?"
 ],
 "股票和基金区别": [
  "Stocks vs. funds",
  "株式とファンドの違い",
  "주식과 펀드의 차이",
  "Actions vs fonds"
 ],
 "如何看财报": [
  "How to read financial reports",
  "決算書の読み方",
  "재무제표 보는 법",
  "Lire un rapport financier"
 ],
 "什么是止损": [
  "What is a stop-loss?",
  "損切りとは？",
  "손절이란?",
  "Qu'est-ce qu'un stop-loss ?"
 ],
 "分散投资原则": [
  "Diversification principles",
  "分散投資の原則",
  "분산 투자 원칙",
  "Principes de diversification"
 ],
 "仅供学习，不构成投资建议": [
  "For learning only. Not investment advice.",
  "学習目的のみ。投資助言ではありません。",
  "학습용입니다. 투자 조언이 아닙니다.",
  "À but éducatif. Pas un conseil en investissement."
 ],
 "输入问题…": [
  "Ask a question…",
  "質問を入力…",
  "질문을 입력하세요…",
  "Posez une question…"
 ],
 "关于": [
  "About",
  "このアプリについて",
  "정보",
  "À propos"
 ],
 "开发者": [
  "Developer",
  "開発者",
  "개발자",
  "Développeur"
 ],
 "网站": [
  "Website",
  "ウェブサイト",
  "웹사이트",
  "Site web"
 ],
 "访问网站": [
  "Visit website",
  "ウェブサイトを開く",
  "웹사이트 방문",
  "Visiter le site"
 ],
 "法律": [
  "Legal",
  "法的情報",
  "법적 고지",
  "Mentions légales"
 ],
 "隐私政策 / Privacy Policy": [
  "Privacy Policy",
  "プライバシーポリシー",
  "개인정보 처리방침",
  "Politique de confidentialité"
 ],
 "免责声明": [
  "Disclaimer",
  "免責事項",
  "면책 조항",
  "Avertissement"
 ],
 "本应用仅供学习和教育目的，不构成任何投资建议。股市有风险，投资需谨慎。行情数据可能存在延迟。AI 老师内容由 AI 生成，仅供参考。": [
  "This app is for learning and education only and does not constitute investment advice. Investing involves risk. Market data may be delayed. AI Teacher content is AI-generated and for reference only.",
  "本アプリは学習・教育目的のみで、投資助言ではありません。投資にはリスクが伴います。相場データは遅延する場合があります。AI先生の内容はAIが生成したもので、参考情報です。",
  "이 앱은 학습 및 교육 목적이며 투자 조언이 아닙니다. 투자에는 위험이 따르며 시세 데이터는 지연될 수 있습니다. AI 선생님의 내용은 AI가 생성한 참고용 정보입니다.",
  "Cette application est à but éducatif et ne constitue pas un conseil en investissement. Investir comporte des risques. Les données peuvent être différées. Le contenu du Prof IA est généré par IA, à titre indicatif."
 ],
 "数据": [
  "Data",
  "データ",
  "데이터",
  "Données"
 ],
 "数据说明": [
  "About your data",
  "データについて",
  "데이터 안내",
  "À propos de vos données"
 ],
 "模拟盘数据和 AI 对话记录存储在服务器上，通过设备匿名 ID 关联，不绑定任何个人身份。重置账户将永久删除所有相关数据。": [
  "Paper-trading data and AI chats are stored on our server and linked to an anonymous device ID, not to any personal identity. Resetting the account permanently deletes the related data.",
  "ペーパートレードのデータとAIとの会話は、端末の匿名IDに紐づけてサーバーに保存され、個人を特定する情報とは結びつきません。口座をリセットすると関連データは完全に削除されます。",
  "모의투자 데이터와 AI 대화 기록은 기기 익명 ID로 서버에 저장되며 개인 신원과 연결되지 않습니다. 계좌를 초기화하면 관련 데이터가 영구 삭제됩니다.",
  "Les données de simulation et les conversations IA sont stockées sur le serveur, liées à un identifiant d'appareil anonyme, sans identité personnelle. Réinitialiser le compte supprime définitivement ces données."
 ],
 "联系 / 删除数据请求": [
  "Contact / data deletion request",
  "お問い合わせ / データ削除の依頼",
  "문의 / 데이터 삭제 요청",
  "Contact / demande de suppression"
 ],
 "Best Friend Stock · 版本 1.0": [
  "Best Friend Stock · Version 1.0",
  "Best Friend Stock · バージョン 1.0",
  "Best Friend Stock · 버전 1.0",
  "Best Friend Stock · Version 1.0"
 ],
 "全球市场": [
  "Global Markets",
  "グローバル市場",
  "글로벌 시장",
  "Marchés mondiaux"
 ],
 "美股情绪": [
  "US Sentiment",
  "米国株センチメント",
  "미국 주식 심리",
  "Sentiment US"
 ],
 "A股情绪": [
  "A-Share Sentiment",
  "A株センチメント",
  "A주 심리",
  "Sentiment A"
 ],
 "极度恐慌": [
  "Extreme Fear",
  "極度の恐怖",
  "극단적 공포",
  "Peur extrême"
 ],
 "恐慌": [
  "Fear",
  "恐怖",
  "공포",
  "Peur"
 ],
 "贪婪": [
  "Greed",
  "強欲",
  "탐욕",
  "Avidité"
 ],
 "极度贪婪": [
  "Extreme Greed",
  "極度の強欲",
  "극단적 탐욕",
  "Avidité extrême"
 ],
 "清空对话": [
  "Clear chat",
  "会話を消去",
  "대화 지우기",
  "Effacer la conversation"
 ],
 "停止生成": [
  "Stop generating",
  "生成を停止",
  "생성 중지",
  "Arrêter la génération"
 ],
 "发送": [
  "Send",
  "送信",
  "보내기",
  "Envoyer"
 ],
 "重置账户": [
  "Reset account",
  "口座をリセット",
  "계좌 초기화",
  "Réinitialiser le compte"
 ],
 "加入自选": [
  "Add to watchlist",
  "ウォッチリストに追加",
  "관심종목에 추가",
  "Ajouter aux favoris"
 ],
 "减少": [
  "Decrease",
  "減らす",
  "줄이기",
  "Diminuer"
 ],
 "增加": [
  "Increase",
  "増やす",
  "늘리기",
  "Augmenter"
 ],
 "美股大盘": [
  "US Market",
  "米国市場",
  "미국 시장",
  "Marché américain"
 ],
 "盘前交易": [
  "Pre-market",
  "プレマーケット",
  "프리마켓",
  "Pré-ouverture"
 ],
 "交易中": [
  "Market open",
  "取引中",
  "거래 중",
  "Marché ouvert"
 ],
 "盘后交易": [
  "After-hours",
  "時間外取引",
  "애프터마켓",
  "Après-clôture"
 ],
 "休市": [
  "Closed",
  "休場",
  "휴장",
  "Fermé"
 ],
 "距开盘 %@": [
  "Opens in %@",
  "開場まで %@",
  "개장까지 %@",
  "Ouverture dans %@"
 ],
 "%lld小时 %lld分钟": [
  "%lld h %lld min",
  "%lld時間%lld分",
  "%lld시간 %lld분",
  "%lld h %lld min"
 ],
 "%lld天": [
  "%lld d",
  "%lld日",
  "%lld일",
  "%lld j"
 ],
 "市盈率": [
  "P/E",
  "PER",
  "PER",
  "P/E"
 ],
 "总市值": [
  "Market cap",
  "時価総額",
  "시가총액",
  "Capi. boursière"
 ],
 "52周最低": [
  "52W low",
  "52週安値",
  "52주 최저",
  "Plus bas 52 sem."
 ],
 "52周最高": [
  "52W high",
  "52週高値",
  "52주 최고",
  "Plus haut 52 sem."
 ],
 "财报日历": [
  "Earnings calendar",
  "決算カレンダー",
  "실적 캘린더",
  "Calendrier des résultats"
 ],
 "预期 EPS %@": [
  "Est. EPS %@",
  "予想EPS %@",
  "예상 EPS %@",
  "BPA prév. %@"
 ],
 "盘前": [
  "Pre-mkt",
  "寄り前",
  "장전",
  "Avant ouv."
 ],
 "盘后": [
  "After-mkt",
  "引け後",
  "장후",
  "Après clôt."
 ],
 "未来一周暂无重要财报": [
  "No major earnings this week",
  "今週の主要決算はありません",
  "이번 주 주요 실적 발표 없음",
  "Aucun résultat majeur cette semaine"
 ],
 "日内振幅": [
  "Day range",
  "日中値幅",
  "일일 변동폭",
  "Amplitude"
 ],
 "资讯": [
  "News",
  "ニュース",
  "뉴스",
  "Actualités"
 ],
 "每日新闻": [
  "Daily news",
  "デイリーニュース",
  "오늘의 뉴스",
  "Actualités du jour"
 ],
 "大行观点": [
  "Bank views",
  "大手行の見方",
  "대형 은행 전망",
  "Avis des banques"
 ],
 "暂无资讯": [
  "No news yet",
  "ニュースはまだありません",
  "아직 뉴스가 없습니다",
  "Aucune actualité"
 ],
 "加载失败": [
  "Failed to load",
  "読み込みに失敗しました",
  "불러오기 실패",
  "Échec du chargement"
 ],
 "综合评分": [
  "Stock score",
  "総合スコア",
  "종합 점수",
  "Score global"
 ],
 "技术面": [
  "Technical",
  "テクニカル",
  "기술적",
  "Technique"
 ],
 "基本面": [
  "Fundamental",
  "ファンダメンタル",
  "펀더멘털",
  "Fondamentaux"
 ],
 "情绪面": [
  "Sentiment",
  "センチメント",
  "심리",
  "Sentiment"
 ],
 "风险": [
  "Risk",
  "リスク",
  "위험",
  "Risque"
 ],
 "评级": [
  "Rating",
  "格付け",
  "투자의견",
  "Notation"
 ],
 "目标价": [
  "Price target",
  "目標株価",
  "목표가",
  "Objectif de cours"
 ],
 "展望": [
  "Outlook",
  "見通し",
  "전망",
  "Perspectives"
 ],
 "宏观": [
  "Macro",
  "マクロ",
  "거시",
  "Macro"
 ],
 "策略": [
  "Strategy",
  "ストラテジー",
  "전략",
  "Stratégie"
 ],
 "今日知识": [
  "Today's concept",
  "今日の知識",
  "오늘의 지식",
  "Notion du jour"
 ],
 "全球商学院指南": [
  "Business school guide",
  "ビジネススクールガイド",
  "글로벌 비즈니스 스쿨 가이드",
  "Guide des business schools"
 ],
 "搜索商学院": [
  "Search schools",
  "スクールを検索",
  "학교 검색",
  "Rechercher une école"
 ],
 "北美": [
  "North America",
  "北米",
  "북미",
  "Amérique du Nord"
 ],
 "英国": [
  "UK",
  "英国",
  "영국",
  "Royaume-Uni"
 ],
 "欧洲": [
  "Europe",
  "ヨーロッパ",
  "유럽",
  "Europe"
 ],
 "亚洲": [
  "Asia",
  "アジア",
  "아시아",
  "Asie"
 ],
 "大洋洲": [
  "Oceania",
  "オセアニア",
  "오세아니아",
  "Océanie"
 ],
 "拉美及其他": [
  "Latin America & other",
  "中南米・その他",
  "중남미 및 기타",
  "Amérique latine et autres"
 ],
 "综合排名": [
  "Overall",
  "総合ランキング",
  "종합 순위",
  "Classement général"
 ],
 "商科排名": [
  "Business",
  "ビジネス分野",
  "경영학 순위",
  "Business"
 ],
 "QS 商科 #%@": [
  "QS Business #%@",
  "QS ビジネス #%@",
  "QS 경영학 #%@",
  "QS Business #%@"
 ],
 "QS 综合 #%@": [
  "QS overall #%@",
  "QS 総合 #%@",
  "QS 종합 #%@",
  "QS général #%@"
 ],
 "综合 #%@": [
  "Overall #%@",
  "総合 #%@",
  "종합 #%@",
  "Général #%@"
 ],
 "独立商学院": [
  "Standalone school",
  "単科ビジネススクール",
  "독립 경영대학원",
  "École indépendante"
 ],
 "商科比综合高 %lld 位": [
  "%lld places above overall",
  "総合より %lld 位上",
  "종합보다 %lld위 높음",
  "%lld places au-dessus du général"
 ],
 "商科排名只看商学与管理学科的声誉和研究；不少学校的商科远高于综合排名。": [
  "This ranking looks only at business and management reputation and research, so many schools rank far higher here than overall.",
  "この分野別ランキングはビジネス・経営学の評判と研究のみを評価するため、総合順位より大きく上位になる大学が多くあります。",
  "경영학 분야의 평판과 연구만 평가하므로 종합 순위보다 훨씬 높은 학교가 많습니다.",
  "Ce classement ne retient que la réputation et la recherche en gestion : beaucoup d'écoles y sont bien mieux placées qu'au classement général."
 ],
 "来源：QS 商科排名 2026 · QS 综合排名 2027": [
  "Sources: QS Business & Management Studies 2026 · QS World University Rankings 2027",
  "出典：QS ビジネス・経営学 2026 · QS 世界大学ランキング 2027",
  "출처: QS 경영학 2026 · QS 세계대학순위 2027",
  "Sources : QS Business & Management Studies 2026 · QS World University Rankings 2027"
 ],
 "项目": [
  "Programs",
  "プログラム",
  "프로그램",
  "Programmes"
 ],
 "专业方向": [
  "Specialties",
  "専門分野",
  "전공 분야",
  "Spécialités"
 ],
 "申请要求": [
  "Admission",
  "出願要件",
  "지원 요건",
  "Admission"
 ],
 "就业去向": [
  "Employment",
  "就職先",
  "취업 분야",
  "Débouchés"
 ],
 "知名校友": [
  "Notable alumni",
  "著名な卒業生",
  "유명 동문",
  "Anciens célèbres"
 ],
 "访问官网": [
  "Visit website",
  "公式サイトを開く",
  "공식 웹사이트",
  "Site officiel"
 ],
 "创办": [
  "Founded",
  "創立",
  "설립",
  "Fondée"
 ],
 "学费": [
  "Tuition",
  "学費",
  "학비",
  "Frais"
 ],
 "授课语言": [
  "Language",
  "授業言語",
  "수업 언어",
  "Langue"
 ],
 "接受": [
  "Accepted",
  "可",
  "인정",
  "Accepté"
 ],
 "不接受": [
  "Not accepted",
  "不可",
  "불가",
  "Non accepté"
 ],
 "商学院指南": [
  "Business schools",
  "ビジネススクール",
  "비즈니스 스쿨",
  "Business schools"
 ],
 "QS 商科排名前 150 + 90 所商学院的学费与申请要求": [
  "QS business ranking top 150, plus tuition and admission for 90 schools",
  "QS ビジネス分野トップ150と90校の学費・出願要件",
  "QS 경영학 순위 150위와 90개 학교의 학비·지원 요건",
  "Top 150 QS en business, frais et admission de 90 écoles"
 ],
 "求职指南": [
  "Career guide",
  "キャリアガイド",
  "커리어 가이드",
  "Guide carrière"
 ],
 "了解8个金融岗位：日常工作、技能、薪资，还能模拟面试": [
  "8 finance roles: daily work, skills, pay — plus mock interviews",
  "金融8職種の仕事内容・スキル・年収と模擬面接",
  "금융 8개 직무: 업무·역량·연봉과 모의 면접",
  "8 métiers de la finance : quotidien, compétences, salaires et entretiens simulés"
 ],
 "典型场景": [
  "Typical scenario",
  "典型的なシーン",
  "대표 상황",
  "Scénario type"
 ],
 "典型的一天": [
  "A typical day",
  "典型的な一日",
  "하루 일과",
  "Une journée type"
 ],
 "核心技能": [
  "Core skills",
  "コアスキル",
  "핵심 역량",
  "Compétences clés"
 ],
 "与相近岗位的区别": [
  "How it differs",
  "近い職種との違い",
  "유사 직무와의 차이",
  "Différences avec les métiers proches"
 ],
 "证书建议": [
  "Certifications",
  "おすすめ資格",
  "추천 자격증",
  "Certifications"
 ],
 "入门门槛": [
  "Entry requirements",
  "応募条件",
  "진입 요건",
  "Conditions d'accès"
 ],
 "职业路径": [
  "Career path",
  "キャリアパス",
  "커리어 경로",
  "Parcours de carrière"
 ],
 "薪资参考": [
  "Pay range",
  "給与の目安",
  "연봉 참고",
  "Fourchette de salaire"
 ],
 "模拟面试": [
  "Mock interview",
  "模擬面接",
  "모의 면접",
  "Entretien simulé"
 ],
 "技术面试": [
  "Technical",
  "技術面接",
  "기술 면접",
  "Technique"
 ],
 "行为面试": [
  "Behavioral",
  "行動面接",
  "인성 면접",
  "Comportemental"
 ],
 "综合面试": [
  "Comprehensive",
  "総合面接",
  "종합 면접",
  "Complet"
 ],
 "AI面试官会一次问一个问题，4-5轮后给出评分和改进建议": [
  "The AI interviewer asks one question at a time and scores you after 4-5 rounds",
  "AI面接官が1問ずつ質問し、4〜5往復後に採点とアドバイスをします",
  "AI 면접관이 한 번에 한 문제씩 묻고 4~5회 후 점수와 조언을 줍니다",
  "L'IA pose une question à la fois et vous note après 4 à 5 échanges"
 ],
 "开始面试": [
  "Start interview",
  "面接を始める",
  "면접 시작",
  "Commencer"
 ],
 "重新开始": [
  "Restart",
  "やり直す",
  "다시 시작",
  "Recommencer"
 ],
 "输入你的回答…": [
  "Type your answer…",
  "回答を入力…",
  "답변을 입력…",
  "Votre réponse…"
 ],
 "相似走势": [
  "Similar trends",
  "似た値動き",
  "유사 흐름",
  "Tendances similaires"
 ],
 "相关度": [
  "Correlation",
  "相関",
  "상관도",
  "Corrélation"
 ],
 "暂无相似股票": [
  "No similar stocks",
  "似た銘柄はありません",
  "유사 종목 없음",
  "Aucune action similaire"
 ],
 "蒙特卡洛模拟": [
  "Monte Carlo",
  "モンテカルロ",
  "몬테카를로",
  "Monte-Carlo"
 ],
 "3个月": [
  "3M",
  "3か月",
  "3개월",
  "3 mois"
 ],
 "6个月": [
  "6M",
  "6か月",
  "6개월",
  "6 mois"
 ],
 "现在": [
  "Now",
  "現在",
  "현재",
  "Auj."
 ],
 "月": [
  "m",
  "か月",
  "개월",
  "m"
 ],
 "上涨概率": [
  "Chance of gain",
  "上昇確率",
  "상승 확률",
  "Probabilité de hausse"
 ],
 "预期收益": [
  "Expected return",
  "期待収益",
  "기대 수익",
  "Rendement attendu"
 ],
 "中位价格": [
  "Median price",
  "中央値",
  "중앙 가격",
  "Prix médian"
 ],
 "95%最差价": [
  "95% worst case",
  "95%最悪値",
  "95% 최악 가격",
  "Pire cas 95 %"
 ],
 "基于历史收益率和波动率的随机模拟，只是一种可能性的范围，不构成预测或投资建议": [
  "Random simulation from historical returns and volatility: a range of possibilities, not a forecast or investment advice",
  "過去の収益率とボラティリティに基づく乱数シミュレーション。可能性の幅であり、予測や投資助言ではありません",
  "과거 수익률과 변동성에 기반한 무작위 시뮬레이션입니다. 가능성의 범위일 뿐 예측이나 투자 조언이 아닙니다",
  "Simulation aléatoire fondée sur les rendements et la volatilité passés : une fourchette de possibles, ni une prévision ni un conseil"
 ],
 "刚刚": [
  "Just now",
  "たった今",
  "방금",
  "À l'instant"
 ],
 "持仓市值": [
  "Holdings",
  "保有資産",
  "보유 자산",
  "Positions"
 ],
 "总盈亏": [
  "Total P&L",
  "損益合計",
  "총 손익",
  "P&L total"
 ],
 "暂无持仓": [
  "No positions yet",
  "ポジションはありません",
  "보유 종목 없음",
  "Aucune position"
 ],
 "用虚拟资金练习买卖，不承担真实风险": [
  "Practice with virtual cash, no real risk",
  "仮想資金で売買を練習。実際のリスクはありません",
  "가상 자금으로 연습하세요. 실제 위험은 없습니다",
  "Entraînez-vous avec de l'argent virtuel, sans risque réel"
 ],
 "买入第一只股票": [
  "Buy your first stock",
  "最初の銘柄を買う",
  "첫 종목 매수",
  "Acheter une première action"
 ],
 "下一课": [
  "Next lesson",
  "次のレッスン",
  "다음 강의",
  "Leçon suivante"
 ],
 "北京时间": [
  "Beijing time",
  "北京時間",
  "베이징 시간",
  "heure de Pékin"
 ],
 "集合竞价": [
  "Pre-open auction",
  "寄付前",
  "동시호가",
  "Pré-ouverture"
 ],
 "午间休市": [
  "Lunch break",
  "昼休み",
  "점심 휴장",
  "Pause déjeuner"
 ],
 "美股热门": [
  "US Movers",
  "米国株ランキング",
  "미국 주식 순위",
  "Mouvements US"
 ],
 "涨幅榜": [
  "Top gainers",
  "値上がり",
  "상승률",
  "Plus fortes hausses"
 ],
 "跌幅榜": [
  "Top losers",
  "値下がり",
  "하락률",
  "Plus fortes baisses"
 ],
 "活跃榜": [
  "Most active",
  "出来高上位",
  "거래대금",
  "Plus actives"
 ],
 "七巨头": [
  "Magnificent 7",
  "マグニフィセント7",
  "매그니피센트 7",
  "Les 7 Magnifiques"
 ],
 "上涨 %lld · 下跌 %lld": [
  "%lld up · %lld down",
  "上昇 %lld · 下落 %lld",
  "상승 %lld · 하락 %lld",
  "%lld en hausse · %lld en baisse"
 ],
 "数据延迟，仅供参考": [
  "Data may be delayed",
  "データは遅延する場合があります",
  "데이터가 지연될 수 있습니다",
  "Données éventuellement différées"
 ],
 "科技": [
  "Tech",
  "テクノロジー",
  "기술",
  "Technologie"
 ],
 "金融": [
  "Financials",
  "金融",
  "금융",
  "Finance"
 ],
 "能源板块": [
  "Energy",
  "エネルギー",
  "에너지",
  "Énergie"
 ],
 "医疗保健": [
  "Health Care",
  "ヘルスケア",
  "헬스케어",
  "Santé"
 ],
 "非必需消费": [
  "Consumer Disc.",
  "一般消費財",
  "경기소비재",
  "Conso. discrétionnaire"
 ],
 "必需消费": [
  "Consumer Staples",
  "生活必需品",
  "필수소비재",
  "Conso. de base"
 ],
 "工业": [
  "Industrials",
  "資本財",
  "산업재",
  "Industrie"
 ],
 "公用事业": [
  "Utilities",
  "公益事業",
  "유틸리티",
  "Services publics"
 ],
 "原材料": [
  "Materials",
  "素材",
  "소재",
  "Matériaux"
 ],
 "房地产板块": [
  "Real Estate",
  "不動産",
  "부동산",
  "Immobilier"
 ],
 "通信服务": [
  "Communication",
  "通信サービス",
  "커뮤니케이션",
  "Communication"
 ],
 "标普500": [
  "S&P 500",
  "S&P 500",
  "S&P 500",
  "S&P 500"
 ],
 "纳斯达克": [
  "Nasdaq",
  "ナスダック",
  "나스닥",
  "Nasdaq"
 ],
 "道琼斯": [
  "Dow Jones",
  "ダウ平均",
  "다우존스",
  "Dow Jones"
 ],
 "罗素2000": [
  "Russell 2000",
  "ラッセル2000",
  "러셀 2000",
  "Russell 2000"
 ],
 "什么是标普500": [
  "What is the S&P 500?",
  "S&P 500とは？",
  "S&P 500이란?",
  "Qu'est-ce que le S&P 500 ?"
 ],
 "ETF是什么": [
  "What is an ETF?",
  "ETFとは？",
  "ETF란?",
  "Qu'est-ce qu'un ETF ?"
 ],
 "如何看财报季": [
  "How to read earnings season",
  "決算シーズンの見方",
  "어닝 시즌 보는 법",
  "Comprendre la saison des résultats"
 ],
 "什么是做空": [
  "What is short selling?",
  "空売りとは？",
  "공매도란?",
  "Qu'est-ce que la vente à découvert ?"
 ],
 "白酒": [
  "Baijiu",
  "白酒",
  "백주",
  "Baijiu"
 ],
 "银行": [
  "Banks",
  "銀行",
  "은행",
  "Banques"
 ],
 "新能源": [
  "New Energy",
  "新エネルギー",
  "신에너지",
  "Renouvelables"
 ],
 "医药": [
  "Pharma",
  "医薬",
  "제약",
  "Pharma"
 ],
 "消费": [
  "Consumer",
  "消費",
  "소비",
  "Consommation"
 ],
 "军工": [
  "Defense",
  "防衛",
  "방산",
  "Défense"
 ],
 "地产": [
  "Real Estate",
  "不動産",
  "부동산",
  "Immobilier"
 ],
 "能源": [
  "Energy",
  "エネルギー",
  "에너지",
  "Énergie"
 ],
 "电力": [
  "Utilities",
  "電力",
  "전력",
  "Électricité"
 ],
 "化工": [
  "Chemicals",
  "化学",
  "화학",
  "Chimie"
 ],
 "汽车": [
  "Autos",
  "自動車",
  "자동차",
  "Automobile"
 ],
 "传媒": [
  "Media",
  "メディア",
  "미디어",
  "Médias"
 ],
 "加载中...": [
  "Loading...",
  "読み込み中...",
  "불러오는 중...",
  "Chargement..."
 ],
 "重试": [
  "Retry",
  "再試行",
  "다시 시도",
  "Réessayer"
 ],
 "请求超时，请重试": [
  "Request timed out. Please retry.",
  "リクエストがタイムアウトしました。もう一度お試しください。",
  "요청 시간이 초과되었습니다. 다시 시도하세요.",
  "Délai dépassé. Veuillez réessayer."
 ],
 "网络错误": [
  "Network error",
  "ネットワークエラー",
  "네트워크 오류",
  "Erreur réseau"
 ],
 "数据解析失败": [
  "Data parsing failed",
  "データの解析に失敗しました",
  "데이터 해석 실패",
  "Échec de l'analyse des données"
 ],
 "搜索股票": [
  "Search stocks",
  "銘柄を検索",
  "종목 검색",
  "Rechercher une action"
 ],
 "切换到电脑版": [
  "Desktop site",
  "デスクトップ版",
  "PC 버전",
  "Version bureau"
 ],
 "切换到手机版": [
  "Mobile site",
  "モバイル版",
  "모바일 버전",
  "Version mobile"
 ],
 "搜索股票或代码": [
  "Search stocks or tickers",
  "銘柄名・コードで検索",
  "종목명 또는 코드 검색",
  "Rechercher une action ou un symbole"
 ],
 "暂无数据": [
  "No data",
  "データなし",
  "데이터 없음",
  "Aucune donnée"
 ],
 "未找到相关股票": [
  "No stocks found",
  "該当する銘柄がありません",
  "검색 결과가 없습니다",
  "Aucune action trouvée"
 ],
 "返回": [
  "Back",
  "戻る",
  "뒤로",
  "Retour"
 ],
 "日K": [
  "Daily",
  "日足",
  "일봉",
  "Jour"
 ],
 "周K": [
  "Weekly",
  "週足",
  "주봉",
  "Semaine"
 ],
 "月K": [
  "Monthly",
  "月足",
  "월봉",
  "Mois"
 ],
 "近期搜索": [
  "Recent",
  "最近",
  "최근",
  "Récents"
 ],
 "登录后可同步自选股": [
  "Sign in on the desktop site to sync your watchlist",
  "デスクトップ版でログインするとウォッチリストを同期できます",
  "PC 버전에서 로그인하면 관심종목이 동기화됩니다",
  "Connectez-vous sur la version bureau pour synchroniser"
 ],
 "网络似乎不稳定，已显示上次的数据": [
  "Network looks unstable, showing your last data",
  "ネットワークが不安定です。前回のデータを表示しています",
  "네트워크가 불안정합니다. 이전 데이터를 표시합니다",
  "Réseau instable, dernières données affichées"
 ],
 "在 App 内置浏览器中打开": [
  "Opened in an in-app browser",
  "アプリ内ブラウザで開いています",
  "앱 내 브라우저에서 열림",
  "Ouvert dans un navigateur intégré"
 ],
 "用系统浏览器打开": [
  "Open in browser",
  "ブラウザで開く",
  "브라우저에서 열기",
  "Ouvrir dans le navigateur"
 ],
 "更新于 %@": [
  "Updated %@",
  "更新: %@",
  "업데이트: %@",
  "Mis à jour : %@"
 ],
 "买入成功": [
  "Order filled",
  "約定しました",
  "체결되었습니다",
  "Ordre exécuté"
 ],
 "股票代码": [
  "Symbol",
  "銘柄コード",
  "종목 코드",
  "Symbole"
 ],
 "数量": [
  "Shares",
  "数量",
  "수량",
  "Quantité"
 ],
 "最新价": [
  "Price",
  "現在値",
  "현재가",
  "Cours"
 ],
 "涨跌幅": [
  "Change",
  "騰落率",
  "등락률",
  "Variation"
 ],
 "没有持仓": [
  "No positions",
  "保有銘柄なし",
  "보유 종목 없음",
  "Aucune position"
 ]
}
