#!/usr/bin/env python3
"""Builds src/mobile/strings.js from the iOS translation table (single source of truth) plus a few
web-only strings, and fails if a t('...') key used by the mobile UI has no translation.

    python3 frontend/tools/gen_mobile_strings.py
"""
import importlib.util, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("l10n", os.path.join(HERE, "..", "..", "ios", "tools", "l10n_catalog.py"))
l10n = importlib.util.module_from_spec(spec); spec.loader.exec_module(l10n)

# key (Chinese) -> (en, ja, ko, fr); only strings that exist on the web but not in the iOS app
WEB_ONLY = {
    "切换到电脑版": ("Desktop site", "デスクトップ版", "PC 버전", "Version bureau"),
    "切换到手机版": ("Mobile site", "モバイル版", "모바일 버전", "Version mobile"),
    "搜索股票或代码": ("Search stocks or tickers", "銘柄名・コードで検索", "종목명 또는 코드 검색", "Rechercher une action ou un symbole"),
    "暂无数据": ("No data", "データなし", "데이터 없음", "Aucune donnée"),
    "重试": ("Retry", "再試行", "다시 시도", "Réessayer"),
    "加载失败": ("Failed to load", "読み込みに失敗しました", "불러오기 실패", "Échec du chargement"),
    "未找到相关股票": ("No stocks found", "該当する銘柄がありません", "검색 결과가 없습니다", "Aucune action trouvée"),
    "返回": ("Back", "戻る", "뒤로", "Retour"),
    "日K": ("Daily", "日足", "일봉", "Jour"),
    "周K": ("Weekly", "週足", "주봉", "Semaine"),
    "月K": ("Monthly", "月足", "월봉", "Mois"),
    "近期搜索": ("Recent", "最近", "최근", "Récents"),
    "登录后可同步自选股": ("Sign in on the desktop site to sync your watchlist", "デスクトップ版でログインするとウォッチリストを同期できます", "PC 버전에서 로그인하면 관심종목이 동기화됩니다", "Connectez-vous sur la version bureau pour synchroniser"),
    "网络似乎不稳定，已显示上次的数据": ("Network looks unstable, showing your last data", "ネットワークが不安定です。前回のデータを表示しています", "네트워크가 불안정합니다. 이전 데이터를 표시합니다", "Réseau instable, dernières données affichées"),
    "输入问题…": ("Ask a question…", "質問を入力…", "질문을 입력하세요…", "Posez une question…"),
    "在 App 内置浏览器中打开": ("Opened in an in-app browser", "アプリ内ブラウザで開いています", "앱 내 브라우저에서 열림", "Ouvert dans un navigateur intégré"),
    "用系统浏览器打开": ("Open in browser", "ブラウザで開く", "브라우저에서 열기", "Ouvrir dans le navigateur"),
    "更新于 %@": ("Updated %@", "更新: %@", "업데이트: %@", "Mis à jour : %@"),
    "买入成功": ("Order filled", "約定しました", "체결되었습니다", "Ordre exécuté"),
    "股票代码": ("Symbol", "銘柄コード", "종목 코드", "Symbole"),
    "数量": ("Shares", "数量", "수량", "Quantité"),
    "最新价": ("Price", "現在値", "현재가", "Cours"),
    "涨跌幅": ("Change", "騰落率", "등락률", "Variation"),
    "没有持仓": ("No positions", "保有銘柄なし", "보유 종목 없음", "Aucune position"),
}

LANGS = ["en", "ja", "ko", "fr"]
table = {}
for k, v in l10n.T.items(): table[k] = list(v)
for k, v in l10n.EXISTING.items(): table[v[4]] = list(v[:4])      # existing dotted keys: key by Chinese text
for k, v in WEB_ONLY.items(): table[k] = list(v)

src_dir = os.path.join(HERE, "..", "src", "mobile")
used, missing = set(), set()
for root, _, files in os.walk(src_dir):
    for f in files:
        if f.endswith((".jsx", ".js")) and f != "strings.js":
            body = open(os.path.join(root, f), encoding="utf-8").read()
            for m in re.finditer(r"\bt\(\s*(['\"])((?:\\.|(?!\1).)*)\1", body):
                key = m.group(2).replace("\\'", "'").replace('\\"', '"')
                if re.search(r"[一-鿿]", key):
                    used.add(key)
                    if key not in table: missing.add(key)

with open(os.path.join(src_dir, "strings.js"), "w", encoding="utf-8") as f:
    f.write("// GENERATED by frontend/tools/gen_mobile_strings.py (source: ios/tools/l10n_catalog.py). Do not edit.\n")
    f.write("export const LANG_ORDER = ['en', 'ja', 'ko', 'fr']\n")
    f.write("export const STR = " + json.dumps(table, ensure_ascii=False, indent=1) + "\n")

print(f"wrote strings.js: {len(table)} entries, {len(used)} used in mobile UI")
if missing:
    print("MISSING translations for:", *sorted(missing), sep="\n  ")
    sys.exit(1)
